swagger-api/apidom

packages/apidom-parser-adapter-json/src/lexical-analysis/browser-patch.ts
packages/apidom-parser-adapter-yaml-1-2/src/lexical-analysis/browser-patch.ts

This change allows to properly apply the patches
in situations where the WASM file is served on domain
without path.
Refs #1035

fix: amend browser patches

---

packages/apidom-parser-adapter-json/src/lexical-analysis/browser.ts
packages/apidom-parser-adapter-yaml-1-2/src/lexical-analysis/browser.ts

Before the initialization used to be fully eager.
This change introduces complete lazy initialization,
which means first parse request can take longer time.
Initialization is sychronized via a simple lock,
which prevents muptiple initializations running
at the same time. This cased some issues in FireFox.
Rerfs #476

feat(web-tree-sitter): initialize in lazy manner

---

packages/apidom-core/src/index.ts
packages/apidom-core/src/media-types.ts
packages/apidom-ns-asyncapi-2/src/index.ts
packages/apidom-ns-asyncapi-2/src/media-types.ts
packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/message/index.ts
packages/apidom-ns-asyncapi-2/test/refractor/__snapshots__/index.ts.snap
packages/apidom-ns-asyncapi-2/test/refractor/fixtures/asyncapi-2-1-0.json
packages/apidom-ns-asyncapi-2/test/refractor/fixtures/asyncapi-2-2-0.json
packages/apidom-parser-adapter-asyncapi-json-2/src/adapter.ts
packages/apidom-parser-adapter-asyncapi-yaml-2/src/adapter.ts
packages/apidom-playground/src/playground/components/left-pane/EditorControls.jsx
packages/apidom-playground/src/playground/plugin.js
packages/apidom-playground/src/playground/selectors.js
packages/apidom-reference/src/dereference/strategies/asyncapi-2/index.ts
packages/apidom-reference/src/resolve/strategies/asyncapi-2/index.ts
packages/apidom-reference/test/dereference/strategies/asyncapi-2-0/channel-item-object/index.ts
packages/apidom-reference/test/dereference/strategies/asyncapi-2-0/message-object/index.ts
packages/apidom-reference/test/dereference/strategies/asyncapi-2-0/reference-object/index.ts
packages/apidom-reference/test/parse/parsers/apidom-reference-parser-asyncapi-json-2-0/index.ts
packages/apidom-reference/test/parse/parsers/apidom-reference-parser-asyncapi-yaml-2-0/index.ts
packages/apidom-reference/test/resolve/strategies/asyncapi-2-0/channel-item-object/index.ts
packages/apidom-reference/test/resolve/strategies/asyncapi-2-0/reference-object/index.ts

refactor(asyncapi): unify how we work with media types

---

packages/apidom-ns-api-design-systems/test/validator/openapi-3-1/http-request-header-content-type/index.ts
packages/apidom-ns-api-design-systems/test/validator/openapi-3-1/http-request-header/index.ts
packages/apidom-ns-api-design-systems/test/validator/openapi-3-1/http-request-method/index.ts
packages/apidom-ns-api-design-systems/test/validator/openapi-3-1/http-response-status-code/index.ts

We dropped the location information from the annotation message, as the location information can be easily computed from the annotation value sourcemap:
```js
annotation.attributes.get('value').meta.get('sourceMap')
```

test(ns-api-design-systems): fix tests

---

packages/apidom-ls/src/config/asyncapi/message/completion.ts
packages/apidom-ls/src/config/asyncapi/message/lint/content-type.ts
packages/apidom-ls/src/config/asyncapi/message/lint/description.ts
packages/apidom-ls/src/config/asyncapi/message/lint/index.ts
packages/apidom-ls/src/config/asyncapi/message/lint/messageId.ts
packages/apidom-ls/src/config/asyncapi/message/lint/name.ts
packages/apidom-ls/src/config/asyncapi/message/lint/schema-format.ts
packages/apidom-ls/src/config/asyncapi/message/lint/summary.ts
packages/apidom-ls/src/config/codes.ts

This is specific to AsyncAPI 2.4 and Message.messageId
field.
Closes #1429

feat(apidom-ls): support proper completion format for messageId

---

packages/apidom-ls/src/config/asyncapi/server-variable/documentation.ts

This change is specific to AsyncAPI 2.4 spec.
Closes #1423

feat(apidom-ls): add extended docs for Server Variable Object

---

packages/apidom-ls/src/config/asyncapi/operation/completion.ts

This change is specific to AsyncAPI 2.4 spec.
Closes #1434

fix(apidom-ls): fix completion format for Operation.security

---

packages/apidom-ls/src/config/asyncapi/operation-trait/completion.ts
packages/apidom-ls/src/config/asyncapi/operation-trait/documentation.ts
packages/apidom-ls/src/config/asyncapi/operation-trait/meta.ts

This change is specific to AsyncAPI 2.4 spec.
Closes #1435

feat(apidom-ls): add completion for Operation/OperationTrait security

---

packages/apidom-ls/src/config/asyncapi/server-variable/completion.ts
packages/apidom-ls/src/config/asyncapi/server-variable/lint/allowed-fields.ts
packages/apidom-ls/src/config/asyncapi/server/lint/allowed-fields.ts
packages/apidom-ls/src/config/asyncapi/server/lint/protocol-required.ts
packages/apidom-ls/src/config/asyncapi/server/lint/url-required.ts

feat(apidom-ls): support completion/lint for Server/ServerVariable

---

packages/apidom-ls/src/apidom-language-service.ts
packages/apidom-ls/src/apidom-language-types.ts
packages/apidom-ls/src/index.ts
packages/apidom-ls/src/parser-factory.ts
packages/apidom-ls/src/services/completion/completion-service.ts
packages/apidom-ls/src/services/definition/definition-service.ts
packages/apidom-ls/src/services/hover/hover-service.ts
packages/apidom-ls/src/services/validation/validation-service.ts
packages/apidom-ls/src/utils/utils.ts
packages/apidom-ls/test/detect.ts
packages/apidom-ls/test/fixtures/detect/apidom.json
packages/apidom-ls/test/fixtures/detect/apidom.yaml
packages/apidom-ls/test/fixtures/detect/async.json
packages/apidom-ls/test/fixtures/detect/async.yaml
packages/apidom-ls/test/fixtures/detect/oas.json
packages/apidom-ls/test/fixtures/detect/oas.yaml

refs #1582 
addresses #1582 by not defaulting to `asyncapi` namespace for content not recognized as a "known spec" (currently `openapi`, `asyncapi` or `ads`). Still uses internal detection mechanism, following PR will introduced usage of detection logic provided by apidom parser and adapter packages.
It allows to pass a `defaultContentLanguage` to language context, to force detection of a non recognized spec (therfore defaulting to "apidom" namespace) as a spec of given language. Currently supported values are `openap`, `asyncapi`, `ads`
e.g.:
```typescript
const contentLanguage: ContentLanguage = {
namespace: 'asyncapi',
};
const context: LanguageServiceContext = {
metadata: metadata(),
defaultContentLanguage: contentLanguage,
};
const languageService: LanguageService = …
```

feat(apidom-ls): update ns/format detection

---

packages/apidom-playground/scripts/build.js
packages/apidom-playground/scripts/start.js
packages/apidom-reference/config/webpack/browser.config.js
packages/apidom-reference/package.json
packages/apidom-reference/src/index.ts
packages/apidom-reference/src/options/index.ts
packages/apidom-reference/src/resolve/resolvers/FileResolver/index-browser.ts
packages/apidom-reference/src/resolve/resolvers/FileResolver/index-node.ts
packages/apidom-reference/test/resolve/resolvers/FileResolver.ts

fix(reference): make FileResolver isomorphic

---

package-lock.json
packages/apidom-ls/package.json

These include:
- vscode-languageserver-textdocument@1.0.5
- vscode-languageserver-types@3.17.2
Closes #1778
Closes #1777

chore(deps): update dependencies that failed to automerge

---

packages/apidom-parser-adapter-asyncapi-json-2/src/adapter.ts
packages/apidom-parser-adapter-asyncapi-json-2/test/adapter.ts
packages/apidom-parser-adapter-asyncapi-yaml-2/src/adapter.ts
packages/apidom-parser-adapter-asyncapi-yaml-2/test/adapter.ts
packages/apidom-parser-adapter-openapi-json-3-1/src/adapter.ts
packages/apidom-parser-adapter-openapi-json-3-1/test/adapter.ts
packages/apidom-parser-adapter-openapi-yaml-3-1/src/adapter.ts
packages/apidom-parser-adapter-openapi-yaml-3-1/test/adapter.ts

This relates for following adapters:
- asyncapi-json-2
- asyncapi-yaml-2
- openapi-json-3-1
- openapi-yaml-3-1
Refs #1741

fix(adapters): force forward compatible dection to be valid as well

---

package-lock.json
packages/apidom-ast/README.md
packages/apidom-reference/README.md

docs(reference): add example of Axios Request Config and Interceptors

---

packages/apidom-ns-asyncapi-2/src/refractor/specification.ts
packages/apidom-ns-asyncapi-2/test/refractor/elements/Schema/__snapshots__/index.ts.snap
packages/apidom-ns-asyncapi-2/test/refractor/elements/Schema/index.ts

Link Description Object comes from JSON Schema Draft 7.
Refs #1942

feat(ns-asyncapi-2): add support for Link Description Object

---

packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only-absolute-url/dereferenced.json
packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only-absolute-url/ex.json
packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only-absolute-url/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/fixtures/external-only-absolute-url/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/fixtures/external-only-absolute-url/ex.json
packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/fixtures/external-only-absolute-url/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/external-only-absolute-url/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/external-only-absolute-url/ex.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/external-only-absolute-url/root.json
packages/apidom-reference/test/helpers.ts

Test are created for Reference Object from
following specifications:
- OpenAPI 3.0.x
- OpenAPI 3.1.x
- AsyncAPI 2.x.y
Refs #1969

test(reference): add tests for dereference over HTTP

---

packages/apidom-ls/src/config/openapi/config.ts
packages/apidom-ls/src/config/openapi/header/documentation.ts
packages/apidom-ls/src/config/openapi/header/meta.ts

OAS3.1 documentation for `Header` Object
Ref: #1992 
local
fixture:
```yaml
openapi: 3.1.0
info:
title: deref
version: 1.0.0
paths:
/a:
get:
operationId: aget
responses:
'200':
description: a pet to be returned
headers:
X-RateLimit-Limit:
description: Request limit per hour
schema:
type: integer
example: 100
```

feat(ls): oas31 docs for header object

---

packages/apidom-ls/src/config/openapi/header/documentation.ts

feat(ls): add documentation for OpenAPI 3.1.0 Header Object fields

---

packages/apidom-ls/src/config/openapi/config.ts
packages/apidom-ls/src/config/openapi/oauth-flow/documentation.ts
packages/apidom-ls/src/config/openapi/oauth-flow/meta.ts
packages/apidom-ls/src/config/openapi/oauth-flows/documentation.ts
packages/apidom-ls/src/config/openapi/oauth-flows/meta.ts

Ref: #1995,  #1996 
Documentation for OpenApi 3.1.0 `OAuth Flows` Object and `OAuth Flow` Object
Ref: #1995 
Ref: #1996 
local.
fixture:
```yaml
openapi: 3.1.0
info:
title: deref
version: 1.0.0
components:
securitySchemes:
oauth2-server:
type: oauth2
flows:
authorizationCode:
authorizationUrl: 'https://some-url.com/auth'
tokenUrl: 'https://some-url/token'
refreshUrl: 'https://some-url/token'
scopes:
user: allows user resources
admin: allows admin resources
```
`OAuth Flows`:
`OAuth Flow`
`OAuth Flow` target:

feat(ls): docs for OpenApi 3.1.0 OAuth Flow and OAuth Flows objects

---

packages/apidom-ls/src/config/common/schema/documentation.ts

Remove duplicate object in documentation array.
In `/src/config/common/schema/documentation.ts`, there is a duplicate array entry for `externalDocs`.

fix(ls): remove duplicate externalDocs target in documentation

---

packages/apidom-ls/src/config/openapi/contact/documentation.ts

feat(ls): provide OpenAPI 3.0.x Contact obj. docs rules

---

packages/apidom-ls/src/config/openapi/config.ts
packages/apidom-ls/src/config/openapi/media-type/documentation.ts
packages/apidom-ls/src/config/openapi/media-type/meta.ts

Add documentation for OpenApi 3.1.0 Media Type object.
Ref: #1990
local.
fixture:
```yaml
openapi: 3.1.0
info:
title: deref
version: 1.0.0
components:
requestBodies:
sampleEncoding:
content:
multipart/form-data:
schema:
type: object
properties:
id:
type: string
format: uuid
examples:
cat:
summary: An example of a cat
value:
name: Fluffy
petType: Cat
dog:
summary: An example of a dog with a cat's name
value:
name: Puma
petType: Dog
```
parent `multipart/form-data`:
target 1 `multipart/form-data.examples`:
target 2 `multipart/form-data.encoding`:

feat(ls): docs for OpenApi 3.1.0 Media Type object

---

packages/apidom-ls/src/config/openapi/license/documentation.ts

feat(ls): provide OpenAPI 3.0.x License docs rules

---

packages/apidom-ls/src/config/openapi/config.ts
packages/apidom-ls/src/config/openapi/discriminator/documentation.ts
packages/apidom-ls/src/config/openapi/discriminator/meta.ts

- Add documentation for OpenApi 3.1.0 Discriminator Object.
- add custom section for `Additional documentation topics` that provide external links for further reading.
- documentation trimmed per recommendations from https://github.com/swagger-api/apidom/issues/2041#issuecomment-1251822763
@frantuma 
possible todo: add additional context reasoning comments, per https://github.com/swagger-api/apidom/issues/2041#issuecomment-1252058475 
@char0n 
Related issue 1: the `parent` screenshot below required changing this [line](https://github.com/swagger-api/apidom/blob/1bc927e8772711fdbd90f731ff4f330fc6946a3e/packages/apidom-ls/src/config/common/schema/documentation.ts#L175) to include `targetSpec` for AsyncApi
Also another issue 2: visible in the `target` screenshot below, is that the current …

feat(ls): docs for OpenApi 3.1.0 Discriminator object

---

packages/apidom-ls/src/config/openapi/contact/documentation.ts
packages/apidom-ls/src/config/openapi/info/documentation.ts

feat(ls): provide OpenAPI 3.0.x Info docs rules

---

packages/apidom-ls/src/config/openapi/server-variable/completion.ts
packages/apidom-ls/src/config/openapi/server-variable/meta.ts
packages/apidom-ls/src/config/openapi/server/completion.ts
packages/apidom-ls/src/config/openapi/server/meta.ts

Rules are implemented for following specification objects
- Server Object
- Server Variable Object
Refs #2032

OpenAPI 3.0.x language server completion rules

---

packages/apidom-ns-openapi-3-0/src/refractor/visitors/open-api-3-0/distriminator/index.ts
packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/distriminator/index.ts

OpenAPI 3.0.x Discriminator Object doesn't allow using Specification extension inside it.
OpenAPI 3.1.0 Discriminator Object does allow using Specification extension inside it.
This PR fixes the namespace refractor to reflect this.

fix(ns-openapi-3-0): drop support of extensions from Discriminator

---

packages/apidom-ls/src/config/openapi/example/lint/value--mutually-exclusive.ts
packages/apidom-ls/test/fixtures/validation/oas/issue2141.yaml
packages/apidom-ls/test/validate.ts

fixes #2141, updating #2146
the following function is better suited for such cases (check for absence of specific field)
```
linterFunction: 'missingFields',
linterParams: [['value']],
```
the following places the marker on the `value` key (not on the parent)
```
markerTarget: 'value',
```
also added test

fix(apidom-ls): fix OAS example value/externalValue rule

---

packages/apidom-ls/src/config/openapi/server/completion.ts
packages/apidom-ls/src/config/openapi/server/lint/variables--values-type.ts

* documentation for `variables` field
* fix typo in lint rule
Ref: #2061 
Ref: #2062
local

feat(ls): OpenAPI 3.1.0 lint and completion rules for Server object

---

packages/apidom-ls/src/config/openapi/path-item/completion.ts

* add completion rules for OpenAPI 3.1.0 Path Item object
Ref: #2062 
Ref: #2061 (no update required)

feat(ls): provide OpenAPI 3.1.0 completion rules for Path Item object

---

packages/apidom-ls/src/config/openapi/path-item/completion.ts

* remove duplicate entries
* refactor: move related elements differing only by spec version next to each other
followup to #2150

fix(ls): duplicate completion rules for OpenAPI 3.1.0 Path Item

---

packages/apidom-ls/src/config/openapi/operation/completion.ts

Ref: #2062 
Ref: #2061 (no update required)

feat(ls): provide OpenAPI 3.1.0 completion rules for Operation object

---

package-lock.json
packages/apidom-ls/src/services/definition/definition-service.ts
packages/apidom-ls/src/services/deref/deref-service.ts
packages/apidom-ls/src/services/hover/hover-service.ts
packages/apidom-reference/README.md
packages/apidom-reference/package.json
packages/apidom-reference/src/resolve/resolvers/FileResolver/index-node.ts
packages/apidom-reference/src/resolve/resolvers/HttpResolverAxios.ts
packages/apidom-reference/src/resolve/util.ts
packages/apidom-reference/src/types.ts
packages/apidom-reference/test/mocha-bootstrap.cjs
packages/apidom-reference/test/resolve/index.ts
packages/apidom-reference/test/resolve/resolvers/FileResolver.ts

Refs #2154
BREAKING CHANGE: FileResolver will not detect and process any local file unless explicitly allowed by fileAllowList option

feat(reference): add support for file allow list for FileResolver

---

packages/apidom-reference/src/parse/index.ts
packages/apidom-reference/src/resolve/util.ts

Bounding options now happens before filtering resolver and parser plugins.

fix(reference): bound options during resolution and parsing

---

packages/apidom-ls/src/config/openapi/oauth-flows/completion.ts

provide OpenAPI 3.1.0 completion rules for OAuth Flows
Ref: #2062 
Ref: #2061 (no update required)

feat(ls): provide OpenAPI 3.1.0 completion rules for OAuth Flows

---

packages/apidom-ls/src/config/openapi/oauth-flow/completion.ts

provide OpenAPI 3.1.0 completion rules for OAuth Flow
Ref: #2062 
Ref: #2061 (no update required)

feat(ls): provide OpenAPI 3.1.0 completion rules for OAuth Flow

---

packages/apidom-ls/src/config/openapi/server-variable/completion.ts

provide OpenAPI 3.1.0 completion for Server Variable object
Ref: #2062

feat(ls): provide OpenAPI 3.1.0 completion for Server Variable object

---

.browserslistrc
packages/apidom-ast/config/webpack/browser.config.js
packages/apidom-core/config/webpack/browser.config.js
packages/apidom-json-path/config/webpack/browser.config.js
packages/apidom-json-pointer/config/webpack/browser.config.js
packages/apidom-ls/config/webpack/browser.config.js
packages/apidom-ns-api-design-systems/config/webpack/browser.config.js
packages/apidom-ns-asyncapi-2/config/webpack/browser.config.js
packages/apidom-ns-json-schema-draft-4/config/webpack/browser.config.js
packages/apidom-ns-json-schema-draft-6/config/webpack/browser.config.js
packages/apidom-ns-json-schema-draft-7/config/webpack/browser.config.js
packages/apidom-ns-openapi-3-0/config/webpack/browser.config.js
packages/apidom-ns-openapi-3-1/config/webpack/browser.config.js
packages/apidom-parser-adapter-api-design-systems-json/config/webpack/browser.config.js
packages/apidom-parser-adapter-api-design-systems-yaml/config/webpack/browser.config.js
packages/apidom-parser-adapter-asyncapi-json-2/config/webpack/browser.config.js
packages/apidom-parser-adapter-asyncapi-yaml-2/config/webpack/browser.config.js
packages/apidom-parser-adapter-json/config/webpack/browser.config.js
packages/apidom-parser-adapter-openapi-json-3-0/config/webpack/browser.config.js
packages/apidom-parser-adapter-openapi-json-3-1/config/webpack/browser.config.js
packages/apidom-parser-adapter-openapi-yaml-3-0/config/webpack/browser.config.js
packages/apidom-parser-adapter-openapi-yaml-3-1/config/webpack/browser.config.js
packages/apidom-parser-adapter-yaml-1-2/config/webpack/browser.config.js
packages/apidom-parser/config/webpack/browser.config.js
packages/apidom-reference/config/webpack/browser.config.js

Along with new browserslist, eliminate all the webpack performance warnings.
Refs #1414

feat(build): build UMD fragments with new browserslist

---

packages/apidom-ls/src/config/openapi/callback/completion.ts
packages/apidom-ls/src/config/openapi/callback/meta.ts
packages/apidom-ls/src/config/openapi/example/completion.ts
packages/apidom-ls/src/config/openapi/header/completion.ts
packages/apidom-ls/src/config/openapi/link/completion.ts
packages/apidom-ls/src/config/openapi/parameter/completion.ts
packages/apidom-ls/src/config/openapi/request-body/completion.ts
packages/apidom-ls/src/config/openapi/response/completion.ts
packages/apidom-ls/src/config/openapi/security-scheme/completion.ts

feat(ls): provide completion rules for $ref field in supported objects

---

packages/apidom-ls/src/config/openapi/discriminator/lint/allowed-fields-3-1.ts
packages/apidom-ls/src/config/openapi/discriminator/lint/index.ts

This change is specific to OpenAPI 3.1.0.
Refs #2061

fix(ls): provide spec extension lint rule for Discriminator

---

packages/apidom-ls/src/config/openapi/request-body/lint/allowed-fields-3-1.ts
packages/apidom-ls/src/config/openapi/request-body/lint/index.ts

fix(ls): provide OpenAPI 3.1 Request Body allowed fields lint rule

---

packages/apidom-ns-asyncapi-2/src/elements/bindings/kafka/KafkaChannelBinding.ts
packages/apidom-ns-asyncapi-2/src/elements/bindings/kafka/KafkaMessageBinding.ts
packages/apidom-ns-asyncapi-2/src/elements/bindings/kafka/KafkaServerBinding.ts
packages/apidom-ns-asyncapi-2/src/elements/bindings/nats/NatsOperationBinding.ts

feat(ns-asyncapi-2): add latest bindings versions in elements layer

---

packages/apidom-ls/src/config/asyncapi/bindings/amqp/message-binding/meta.ts
packages/apidom-ls/src/config/asyncapi/bindings/amqp/operation-binding/meta.ts
packages/apidom-ls/src/config/asyncapi/bindings/kafka/server-binding/meta.ts

Some of the completions where not connected to meta objects.

fix(ls): enable completion for AsyncAPI binding objects

---

packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/parsers/json/index.ts

This plugin mimics the JSON parsing mechanism of swagger-client.
Refs #2317

test(reference): add swagger-client JSON parser plugin

---

packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/parsers/yaml1-2/index.ts

This plugin mimics the YAML parsing mechanism from swagger-client.
Refs #2320

test(reference): add swaggeer-client YAML parser plugin

---

packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/helpers/parsers/openapi-yaml-3-1/index.ts

This plugin mimics the YAML parsing mechanism from swagger-client.
Refs #2324

test(reference): add swagger-client OpenAPI 3.1 YAML parser plugin

---

packages/apidom-reference/src/dereference/strategies/openapi-3-1-swagger-client/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1-swagger-client/visitor.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-external/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-external/ex1.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-external/ex2.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-external/ex3.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-external/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-internal/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/fixtures/meta-patches-internal/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-external/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-external/ex1.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-external/ex2.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-external/ex3.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-external/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-internal/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/fixtures/meta-patches-internal/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-external/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-external/ex1.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-external/ex2.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-external/ex3.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-external/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-internal/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/meta-patches-internal/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.ts

This affects OpenAPI 3.1 swagger-client dereference strategy.
Refs #2336

feat(reference): add support for allowMetaPatches option

---

packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameters.ts
packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-security-requirements.ts
packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-servers.ts

This will allow refractor plugin composition.
When returning false, other plugins will not be
able to intercept the skipped nodes.

fix(ns-openapi-3-1): avoid returning false in ractor plugins

---

packages/apidom-ns-openapi-3-1/README.md
packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-operation-ids.ts

Docs has been provided for following plugins:
- refractorPluginNormalizeParameters
- refractorPluginNormalizeSecurityRequirements
- refractorPluginNormalizeServers
- refractorPluginNormalizeOperationIds
Refs #2362

docs(ns-openapi-3-1): provide docs for refractor plugins

---

packages/apidom-reference/src/dereference/strategies/openapi-3-1-swagger-client/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/uri/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-1/util.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/$ref-url-relative-reference/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/fixtures/$ref-url-relative-reference/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$ref-url-relative-reference/dereferenced.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$ref-url-relative-reference/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts

Affected by this commit are OpenAPI 3.1 related dereference and resolution strategies. BaseURI is now properly resolved from  and  keywords.

fix(reference): fix OpenAPI 3.1 Schema Object resolution

---

package-lock.json
packages/apidom-reference/package.json
packages/apidom-reference/src/configuration/empty.ts
packages/apidom-reference/src/configuration/saturated.ts
packages/apidom-reference/src/index.ts
packages/apidom-reference/src/options/index.ts
packages/apidom-reference/test/mocha-bootstrap.cjs
packages/apidom-reference/test/resolve/index.ts

Configuration of options has been extracted into
configuration/ module. This allowed to separate
all abstractions from the configuration.
apidom-reference package now exports two types
of configuration - saturated and empty.
Saturated configuration setups all the package components and wire them into options.
Empty configuration setups empty options.
sideEffects package.json field has been turned on for the satured configuration.
Subpath exports has been utilized to allow importing individual components without importing everything.
Refs #2718

feat(reference): separate abstractions from configuration

---

packages/apidom-reference/package.json

main fields was to pointing to empty configuration. Fix introduces pointing to saturated configuration.
Refs #2718

fix(reference): fix main field

---

packages/apidom-reference/README.md

docs(reference): document OpenAPI 3.1 swagger-client deref strategy

---

packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/callback-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/example-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/example-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/header-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/link-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/link-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/parameter-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/path-item-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/request-body-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/response-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/schema-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/security-schemes-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/index.ts

test(reference): fix typo in dereference strategy name

---

packages/apidom-reference/package.json
packages/apidom-reference/src/parse/parsers/binary/index-node.ts
packages/apidom-reference/src/resolve/resolvers/file/index-node.ts
packages/apidom-reference/src/util/polyfills/buffer/protocol-import.ts
packages/apidom-reference/src/util/polyfills/buffer/standard-import.ts
packages/apidom-reference/src/util/polyfills/fs/protocol-import.ts
packages/apidom-reference/src/util/polyfills/fs/standard-import.ts
packages/apidom-reference/src/util/polyfills/util/protocol-import.ts
packages/apidom-reference/src/util/polyfills/util/standard-import.ts
packages/apidom-reference/tsconfig.json

This will allow to use ApiDOM with Node.js >= 12.20.0. As exports field condition doesn't allow to specify Node.js versions, when code is requested using require(), non-protocol import fallback will be always used.
Protocol import support is as follows:
- v16.0.0, v14.18.0 (ESM import and CommonJS require())
- v14.13.1, v12.20.0 (only ESM import)

feat(reference): add fallbacks for Node.js protocol imports

---

packages/apidom-ns-openapi-3-0/test/refractor/elements/Schema/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-0/test/refractor/elements/Schema/index.ts

This test guarantees that when Schema.items
is on object, it refracts to Schema. When
Schema.items is array, this array is refracted
into generic array and not array of Schemas.
Refs #2470

test(ns-openapi-3-0): add additional test for Schema.items

---

packages/apidom-core/src/predicates/index.ts
packages/apidom-core/test/predicates/index.ts

As ObjectElement is extension of ArrayElement,
isArrayElement returned true for every ObjectElement instance. Although that was technically correct, it was casing nasty bugs when using isArrayElement.
This commit make the fact that the ObjectElement is extension of ArrayElement an implementation detail, and from now on isArrayElement returns false when asserting on ObjectElement.

fix(core): fix isArrayElement predicate polymorhic characteristics

---

.whitesource
whitesource.config

We've stopped using Whitesource as of 1st January 2023.

chore(SCA): remove all whitesource configs

---

package-lock.json
packages/apidom-ast/package.json
packages/apidom-core/package.json
packages/apidom-json-path/package.json
packages/apidom-json-pointer/package.json
packages/apidom-ls/package.json
packages/apidom-ns-api-design-systems/package.json
packages/apidom-ns-asyncapi-2/package.json
packages/apidom-ns-json-schema-draft-4/package.json
packages/apidom-ns-json-schema-draft-6/package.json
packages/apidom-ns-json-schema-draft-7/package.json
packages/apidom-ns-openapi-3-0/package.json
packages/apidom-ns-openapi-3-1/package.json
packages/apidom-ns-workflows-1/package.json
packages/apidom-parser-adapter-api-design-systems-json/package.json
packages/apidom-parser-adapter-api-design-systems-yaml/package.json
packages/apidom-parser-adapter-asyncapi-json-2/package.json
packages/apidom-parser-adapter-asyncapi-yaml-2/package.json
packages/apidom-parser-adapter-json/package.json
packages/apidom-parser-adapter-openapi-json-3-0/package.json
packages/apidom-parser-adapter-openapi-json-3-1/package.json
packages/apidom-parser-adapter-openapi-yaml-3-0/package.json
packages/apidom-parser-adapter-openapi-yaml-3-1/package.json
packages/apidom-parser-adapter-yaml-1-2/package.json
packages/apidom-parser/package.json
packages/apidom-reference/package.json

With this change we will avoid webpack aliases.
Refs #2562

fix(deps): relax @babel/runtime-corejs3 version

---

package-lock.json
packages/apidom-ast/package.json
packages/apidom-core/package.json
packages/apidom-json-path/package.json
packages/apidom-json-pointer/package.json
packages/apidom-ns-api-design-systems/package.json
packages/apidom-ns-asyncapi-2/package.json
packages/apidom-ns-json-schema-draft-4/package.json
packages/apidom-ns-json-schema-draft-6/package.json
packages/apidom-ns-json-schema-draft-7/package.json
packages/apidom-ns-openapi-3-0/package.json
packages/apidom-ns-openapi-3-1/package.json
packages/apidom-ns-workflows-1/package.json
packages/apidom-parser-adapter-api-design-systems-json/package.json
packages/apidom-parser-adapter-api-design-systems-yaml/package.json
packages/apidom-parser-adapter-asyncapi-json-2/package.json
packages/apidom-parser-adapter-asyncapi-yaml-2/package.json
packages/apidom-parser-adapter-json/package.json
packages/apidom-parser-adapter-openapi-json-3-0/package.json
packages/apidom-parser-adapter-openapi-json-3-1/package.json
packages/apidom-parser-adapter-openapi-yaml-3-0/package.json
packages/apidom-parser-adapter-openapi-yaml-3-1/package.json
packages/apidom-parser-adapter-yaml-1-2/package.json
packages/apidom-parser/package.json

ApiDOM side effects handling for bundlers

---

package-lock.json
packages/apidom-reference/package.json

When parser adapters (or other ApiDOM deps) fail to install, one can still use empty configuration.
Refs #2590

feat(reference): mark the deps from saturated config as optional

---

packages/apidom-parser-adapter-json/test/adapter-node.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts

Refs https://github.com/swagger-api/swagger-ui/issues/8537

fix(reference): use parent in ancestors lineage

---

packages/apidom-ls/src/services/completion/completion-service.ts

Before this change, completion items were only
provided if they started by the filtered text.
With this change, completion items are provided
if they include filtered text.
Refs https://github.com/swagger-api/swagger-editor/issues/3216

fix(ls): provide completion items with proper filtering

---

packages/apidom-reference/package.json
packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/uri/index.ts
packages/apidom-reference/test/perf/.eslintrc
packages/apidom-reference/test/perf/fixtures/openapi-3-1.json
packages/apidom-reference/test/perf/index.cjs
packages/apidom-reference/test/perf/openapi-3-1-dereference.cjs

perf(reference): add caching capability for OpenAPI 3.1 uri selector

---

package-lock.json
packages/apidom-ns-json-schema-draft-4/package.json
packages/apidom-ns-openapi-3-1/package.json

This affected following packages:
- ns-json-schema-draft-4
- ns-openapi-3-1
Refs #2871

fix(deps): add missing @swagger-api/apidom-ast dep

---

packages/apidom-ls/src/config/openapi/server/lint/url--format-uri.ts

Server.url field in not validated as URL if it
contains {variables} inside it.
Refs #2858

fix(ls): fix OpenAPI 3.x.y Server.url field linting

---

.github/dependabot.yml

This is the latest combo of **tree-sitter** related libs that works with YALM grammar (tree-sitter-yaml).
Beyond this versions the YAML grammar still works but the error recovery is non existent anymore.
```json
"tree-sitter": "=0.20.4",
"tree-sitter-cli": "=0.20.4",
"web-tree-sitter": "=0.20.3"
```
Refs #2903

ci(dependabot): ignore updating tree-sitter dependency

---

packages/apidom-ls/src/config/asyncapi/security-scheme/lint/type--equals-2-0.ts
packages/apidom-ls/src/config/asyncapi/security-scheme/lint/type--equals-2-1--2-6.ts
packages/apidom-ls/src/config/openapi/security-scheme/lint/type--equals-3-0.ts
packages/apidom-ls/src/config/openapi/security-scheme/lint/type--equals-3-1.ts

This PR changes the error messages for type linting rules for OpenAPI 3.0.x, OpenAPI 3.1, AsyncAPI 2.0, and AsyncAPI 2.1-2.6 to include the information about allowed values for the type field.
This PR does the following:
- Changes error messages for  OpenAPI 3.0.x, OpenAPI 3.1, AsyncAPI 2.0, and AsyncAPI 2.1-2.6
This change is required to solve this ticket https://smartbear.atlassian.net/browse/SWG-8486 found during OpenAPI 3.1 bug bash. It has been decided that  it would be better to include information about what are the allowed values for type field.
This PR only changes error message text so there are no changes in the package behavior.

feat (apidom-ls): Change error message for type linting rules

---

package.json

Avoids the file permission error during `npm i`.

chore(package): install husky with proper permissions

---

packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/dereference-apidom.ts

This native support includes resolving external and internal
Schema Object references within the fragment.
Refs #2934

feat(reference): support native fragment deref/resolve - Schema Object

---

packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/dereference-apidom.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/dereference-apidom.ts

This native support includes resolving external and internal
references within the OpenAPI 3.0.x fragment.
Refs #2934

feat(reference): support native fragment deref/resolve - OpenAPI 3.0.x

---

.github/workflows/build.yml

@char0n 
lint commit messages job seems to target the wrong commits, including commits not belonging to the branch, see e.g. [this run](https://github.com/swagger-api/apidom/actions/runs/5565788003/jobs/10166426126?pr=2954)
This seems to be related to the check out (by default) of the merge branch instead of the head one, which does mess up somehow commit history, so that  `HEAD~${{ github.event.pull_request.commits }}` for some reason points to a previous non-branch commit. Still kind of mysterious as adding a `git log` to the `HEAD~${{ github.event.pull_request.commits }}`  does point to yet another commit in history..
There might be a better solution, however this PR addresses it by having a separate job `lint-commit-message` do the work, checking out head branch

ci(build): fix branch in lint commit messages

---

packages/apidom-ls/src/apidom-language-types.ts
packages/apidom-ls/src/config/openapi/media-type/completion.ts
packages/apidom-ls/src/services/completion/completion-service.ts
packages/apidom-ls/test/complete.ts
packages/apidom-ls/test/fixtures/openapi-complete-filter.yaml

Refs https://github.com/swagger-api/swagger-editor/issues/4216
This PR introduces support for language service "strict" filtering of completion items, as opt-in based on client passing `enableLSPFilter: true` to `completionContext` (within `languageServiceContext`). 
setting the flag will cause completion items to be filtered vs current word, returning only the ones where `insertText` includes the current word. 
This is an opinionated behaviour, as the default for LSP completions is to leave the filtering logic to the editor/client; Monaco editor always performs fuzzy matching against the `filterText` value and/or the current word, and in the [ticket scenario](https://github.com/swagger-api/swagger-editor/issues/4216) it still displays non "strict matching" items, which is possibly a …

feat: allow apidom-ls strict filter

---

package-lock.json
packages/apidom-ls/src/apidom-language-types.ts
packages/apidom-ls/src/services/completion/completion-service.ts
packages/apidom-ls/src/services/validation/validation-service.ts
packages/apidom-ls/src/utils/utils.ts
packages/apidom-ls/test/fixtures/validation/oas/issue-editor-3626.yaml
packages/apidom-ls/test/validate.ts

Closes swagger-api/swagger-editor/issues/3626

fix(ls): fix validation for indirected local references

---

packages/apidom-ls/src/apidom-language-types.ts
packages/apidom-ls/src/services/completion/completion-service.ts
packages/apidom-ls/src/utils/utils.ts
packages/apidom-ls/test/complete.ts
packages/apidom-ls/test/completion-provider.ts

fixes completion of references:
* doesn't include reference to self
* fixes JSON Pointer paths escaping
* doesn't include by default indirect references (target nodes being a reference themselves). 
Provides a `completionContext` option `includeIndirectRefs`: if set to `true` indirect refs are also included, but only when the document namespace (specification + version) allows for siblings of `$ref` field, as this is the only case where such a reference would make sense. Currently the only namespace supporting this is OpenAPI 3.1

feat(ls): fix  completion paths, self and indirect refs

---

packages/apidom-core/src/elements/SourceMap.ts
packages/apidom-core/src/index.ts
packages/apidom-json-pointer/src/compile.ts
packages/apidom-json-pointer/src/errors/CompilationJsonPointerError.ts
packages/apidom-json-pointer/src/errors/EvaluationJsonPointerError.ts
packages/apidom-json-pointer/src/errors/InvalidJsonPointerError.ts
packages/apidom-json-pointer/src/errors/JsonPointerError.ts
packages/apidom-json-pointer/src/errors/index.ts
packages/apidom-json-pointer/src/evaluate.ts
packages/apidom-json-pointer/src/index.ts
packages/apidom-json-pointer/src/parse.ts

feat(json-pointer): use error hierarchy and metadata when throwing

---

package-lock.json
packages/apidom-json-path/package.json
packages/apidom-json-path/src/errors/EvaluationJsonPathError.ts
packages/apidom-json-path/src/errors/JsonPathError.ts
packages/apidom-json-path/src/errors/MultiEvaluationJsonPathError.ts
packages/apidom-json-path/src/evaluate-multi.ts
packages/apidom-json-path/src/evaluate.ts
packages/apidom-json-path/src/index.ts
packages/apidom-json-pointer/src/compile.ts
packages/apidom-json-pointer/src/evaluate.ts
packages/apidom-json-pointer/src/parse.ts

feat(json-path): use error hierarchy and metadata when throwing

---

babel.config.cjs
packages/apidom-ast/package.json
packages/apidom-core/package.json
packages/apidom-error/package.json
packages/apidom-json-path/package.json
packages/apidom-json-pointer-relative/package.json
packages/apidom-json-pointer/package.json
packages/apidom-ls/package.json
packages/apidom-ns-api-design-systems/package.json
packages/apidom-ns-asyncapi-2/package.json
packages/apidom-ns-json-schema-draft-4/package.json
packages/apidom-ns-json-schema-draft-6/package.json
packages/apidom-ns-json-schema-draft-7/package.json
packages/apidom-ns-openapi-3-0/package.json
packages/apidom-ns-openapi-3-1/package.json
packages/apidom-ns-workflows-1/package.json
packages/apidom-parser-adapter-api-design-systems-json/package.json
packages/apidom-parser-adapter-api-design-systems-yaml/package.json
packages/apidom-parser-adapter-asyncapi-json-2/package.json
packages/apidom-parser-adapter-asyncapi-yaml-2/package.json
packages/apidom-parser-adapter-json/package.json
packages/apidom-parser-adapter-openapi-json-3-0/package.json
packages/apidom-parser-adapter-openapi-json-3-1/package.json
packages/apidom-parser-adapter-openapi-yaml-3-0/package.json
packages/apidom-parser-adapter-openapi-yaml-3-1/package.json
packages/apidom-parser-adapter-yaml-1-2/package.json
packages/apidom-parser/package.json
packages/apidom-reference/package.json

The .mjs extension is reserved for ECMAScript Modules which cannot be loaded via require().

build: use .mjs extension for EcmaScript modules

---

Dockerfile

Some tests were not passing in local docker setup. We needed to pin the emcsriptem to certain version.

fix(docker): make all tests pass in docker setup

---

packages/apidom-ns-openapi-2/README.md
packages/apidom-ns-openapi-2/src/elements/SecurityRequirement.ts
packages/apidom-ns-openapi-2/src/index.ts
packages/apidom-ns-openapi-2/src/media-types.ts
packages/apidom-ns-openapi-2/src/namespace.ts
packages/apidom-ns-openapi-2/src/predicates.ts
packages/apidom-ns-openapi-2/src/refractor/index.ts
packages/apidom-ns-openapi-2/src/refractor/predicates.ts
packages/apidom-ns-openapi-2/src/refractor/registration.ts
packages/apidom-ns-openapi-2/src/refractor/specification.ts
packages/apidom-ns-openapi-2/src/refractor/toolbox.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/FallbackVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/SpecificationExtensionVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/SpecificationVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/Visitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/generics/FixedFieldsVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/generics/MapVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/generics/PatternedFieldsVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/security-requirement/index.ts
packages/apidom-ns-openapi-2/src/traversal/visitor.ts
packages/apidom-ns-openapi-2/test/refractor/elements/SecurityRequirement/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-2/test/refractor/elements/SecurityRequirement/index.ts

feat(ns-openapi-2): add support for Security Requirement Object

---

packages/apidom-ns-openapi-2/README.md
packages/apidom-ns-openapi-2/src/elements/License.ts
packages/apidom-ns-openapi-2/src/index.ts
packages/apidom-ns-openapi-2/src/namespace.ts
packages/apidom-ns-openapi-2/src/predicates.ts
packages/apidom-ns-openapi-2/src/refractor/registration.ts
packages/apidom-ns-openapi-2/src/refractor/specification.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/license/index.ts
packages/apidom-ns-openapi-2/src/traversal/visitor.ts
packages/apidom-ns-openapi-2/test/predicates.ts
packages/apidom-ns-openapi-2/test/refractor/elements/License/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-2/test/refractor/elements/License/index.ts

feat(ns-openapi-2): add support for License Object

---

packages/apidom-ns-openapi-2/README.md
packages/apidom-ns-openapi-2/src/elements/Info.ts
packages/apidom-ns-openapi-2/src/index.ts
packages/apidom-ns-openapi-2/src/namespace.ts
packages/apidom-ns-openapi-2/src/predicates.ts
packages/apidom-ns-openapi-2/src/refractor/registration.ts
packages/apidom-ns-openapi-2/src/refractor/specification.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/info/VersionVisitor.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/info/index.ts
packages/apidom-ns-openapi-2/src/traversal/visitor.ts
packages/apidom-ns-openapi-2/test/predicates.ts
packages/apidom-ns-openapi-2/test/refractor/elements/Info/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-2/test/refractor/elements/Info/index.ts

feat(ns-openapi-2): add support for Info Object

---

packages/apidom-core/src/index.ts
packages/apidom-core/src/predicates/helpers.ts
packages/apidom-core/src/predicates/index.ts
packages/apidom-core/test/predicates/index.ts
packages/apidom-core/test/traversal/filter.ts
packages/apidom-core/test/traversal/find.ts
packages/apidom-ns-api-design-systems/src/predicates.ts
packages/apidom-ns-asyncapi-2/src/predicates.ts
packages/apidom-ns-json-schema-draft-4/src/predicates.ts
packages/apidom-ns-json-schema-draft-6/src/predicates.ts
packages/apidom-ns-json-schema-draft-7/src/predicates.ts
packages/apidom-ns-openapi-2/README.md
packages/apidom-ns-openapi-2/src/predicates.ts
packages/apidom-ns-openapi-3-0/src/predicates.ts
packages/apidom-ns-openapi-3-1/src/predicates.ts
packages/apidom-ns-openapi-3-1/test/refractor/elements/Schema/embedded-resources-$id.ts
packages/apidom-ns-openapi-3-1/test/refractor/elements/Schema/embedded-resources-$schema.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts

feat(predicates): implement TypeScript type guards

---

packages/apidom-core/src/clone/index.ts
packages/apidom-core/test/clone/index.ts

Before this change, deepClone function supported
directed acyclic trees. With this change the
function will handle directed cyclic graphs.
Refs #3290

feat(core): support cycles in deep cloning

---

packages/apidom-ast/src/traversal/visitor.ts
packages/apidom-ast/src/yaml/errors/YamlTagError.ts
packages/apidom-ast/src/yaml/schemas/failsafe/index.ts
packages/apidom-core/src/clone/errors/CloneError.ts
packages/apidom-core/src/deepmerge.ts
packages/apidom-json-path/src/errors/EvaluationJsonPathError.ts
packages/apidom-json-path/src/errors/MultiEvaluationJsonPathError.ts
packages/apidom-json-path/src/evaluate-multi.ts
packages/apidom-json-path/src/evaluate.ts
packages/apidom-json-pointer-relative/src/errors/EvaluationRelativeJsonPointerError.ts
packages/apidom-json-pointer-relative/src/evaluate.ts
packages/apidom-json-pointer/src/errors/EvaluationJsonPointerError.ts
packages/apidom-json-pointer/src/evaluate.ts

refactor: deep clone elements before assigning to structured errrors

---

package-lock.json
packages/apidom-error/package.json
packages/apidom-error/src/ApiDOMAggregateError.ts
packages/apidom-error/src/ApiDOMError.ts
packages/apidom-error/src/ApiDOMStructuredError.ts

This commit remove dependance of ramda and
ramda-adjunct libraries.
It replaces ramda* functions with native
JavaScript features.

refactor(error): use native JavaScript features

---

packages/apidom-ast/src/traversal/visitor.ts
packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-json-schema-draft-4/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-json-schema-draft-6/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-json-schema-draft-7/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-openapi-2/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-openapi-3-0/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-servers.ts
packages/apidom-ns-openapi-3-1/src/refractor/plugins/replace-empty-element.ts
packages/apidom-parser-adapter-json/src/syntactic-analysis/direct/index.ts
packages/apidom-parser-adapter-json/src/syntactic-analysis/indirect/index.ts
packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/index.ts

Array.prototype.at and Array.prototype.findLast are not available in `Node.js 12.20.0` environment and calling them throws `TypeError`. This PR addressed this issue and returns back support for `Node.js >= 12.20.0`.

fix: return support for Node.js >=12.20.0

---

packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/src/dereference/util.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/cycle-internal-advanced/root.json
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts

Refs https://github.com/swagger-api/swagger-ui/issues/9337

fix(reference): fix handling cycles in all dereference strategies

---

packages/apidom-ls/src/config/openapi/contact/completion.ts
packages/apidom-ls/src/config/openapi/contact/documentation.ts
packages/apidom-ls/src/config/openapi/contact/lint/allowed-fields.ts
packages/apidom-ls/src/config/openapi/contact/lint/email--format-email.ts
packages/apidom-ls/src/config/openapi/contact/lint/name--type.ts
packages/apidom-ls/src/config/openapi/contact/lint/url--format-uri.ts
packages/apidom-ls/src/config/openapi/info/lint/contact--type.ts
packages/apidom-ls/src/config/openapi/info/lint/description--type.ts
packages/apidom-ls/src/config/openapi/info/lint/license--type.ts
packages/apidom-ls/src/config/openapi/info/lint/title--required.ts
packages/apidom-ls/src/config/openapi/info/lint/title--type.ts
packages/apidom-ls/src/config/openapi/info/lint/version--required.ts
packages/apidom-ls/src/config/openapi/info/lint/version--type.ts
packages/apidom-ls/src/config/openapi/license/lint/name--required.ts
packages/apidom-ls/src/config/openapi/license/lint/name--type.ts
packages/apidom-ls/src/config/openapi/path-template/lint/value--valid.ts
packages/apidom-ls/src/config/openapi/path-template/lint/value--well-formed.ts
packages/apidom-ls/src/config/openapi/target-specs.ts

This will make sure that when OpenAPI 4.0 lands
existing rules will not be used, unless we
explicitly allow it.
Refs #3104

refactor(ls): make rules scoping forward incompatible

---

packages/apidom-ls/src/config/openapi/swagger/lint/base-path--pattern.ts

Refs #3565 
This PR fixes the regex in the `OPENAPI2_SWAGGER_FIELD_BASE_PATH_PATTERN` linting rule so that it matches on whitespace characters instead of the letter 's'

fix(ls): Fix regex in Swagger 2.0 basePath linting rule

---

packages/apidom-reference/README.md
packages/apidom-reference/package.json
packages/apidom-reference/src/configuration/saturated.ts
packages/apidom-reference/src/parse/parsers/workflows-json-1/index.ts
packages/apidom-reference/test/parse/parsers/workflows-json-1/fixtures/sample-workflow.json
packages/apidom-reference/test/parse/parsers/workflows-json-1/index.ts

feat(reference): add Workflows 1.0.0 JSON parser plugin

---

packages/apidom-ls/src/services/validation/linter-functions.ts
packages/apidom-ls/test/fixtures/validation/oas/parameter-defined-within-path-template-2-0.yaml
packages/apidom-ls/test/fixtures/validation/oas/parameter-defined-within-path-template-3-0.yaml
packages/apidom-ls/test/fixtures/validation/oas/parameter-defined-within-path-template-3-1.yaml
packages/apidom-ls/test/validate.ts

refs #3546 Operation Object parameters

feat(apidom-ls): add operations to parameter lint

---

packages/apidom-ns-openapi-3-0/src/index.ts
packages/apidom-ns-openapi-3-1/src/index.ts

These symbols & types get handy when extending the namespace.

feat(ns-openapi-3-1): export new symbols and types

---

packages/apidom-ast/src/index.ts
packages/apidom-ast/src/yaml/anchors-aliases/ReferenceManager.ts
packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/index.ts
packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
packages/apidom-parser-adapter-yaml-1-2/test/syntactic-analysis/CstVisitor.ts
packages/apidom-parser-adapter-yaml-1-2/test/syntactic-analysis/indirect/visitors/CstVisitor.ts

fix(parser-adapter-yaml-1-2): YAML alias syntactic analysis

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/.eslintrc
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/openapi-version.ts
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/webhooks.ts

This change will make plugins creation much simpler. 
ApiDOM is deep cloned before the plugins touch it.
That way from outside, the converter still remains immutable,
but the plugins work in mutable way.

refactor(converter): allow plugins to perform mutable operations

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type.ts
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/__snapshots__/index.ts.snap
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/fixtures/security-scheme-type.json
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/index.ts

feat(converter): add securitySchemeTypeRefractorPlugin

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/info-summary.ts
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/info-summary/__snapshots__/index.ts.snap
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/info-summary/fixtures/info-summary.json
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/info-summary/index.ts

This plugin removes the `summary` fixed field of `Info Object`.
Refs SWG-9954

feat(converter): add infoSummaryRefractorPlugin

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/license-identifier.ts
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/license-identifier/__snapshots__/index.ts.snap
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/license-identifier/fixtures/license-identifier.json
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/license-identifier/index.ts

feat(converter): add licenseIdentifierRefractorPlugin

---

packages/apidom-core/README.md
packages/apidom-core/src/merge/deepmerge.ts
packages/apidom-core/test/merge/deepmerge.ts

feat(core): customize meta & attributes merges for deepmerge function

---

packages/apidom-ns-openapi-2/src/refractor/index.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/Visitor.ts
packages/apidom-ns-openapi-2/test/refractor/elements/Contact/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-2/test/refractor/elements/Contact/index.ts
packages/apidom-ns-openapi-3-0/src/refractor/index.ts

fix(ns-openapi-2): retain meta & attributes during refracting

---

packages/apidom-ns-api-design-systems/src/refractor/visitors/Visitor.ts
packages/apidom-ns-api-design-systems/test/refractor/elements/Info/__snapshots__/index.ts.snap
packages/apidom-ns-api-design-systems/test/refractor/elements/Info/index.ts
packages/apidom-ns-openapi-2/test/refractor/elements/Contact/index.ts

This change is specific to cases when semantic ApiDOM 
is refractored from generic ApiDOM.
Refs #3842

fix(ns-ads): retain meta & attributes during refracting

---

packages/apidom-ns-asyncapi-2/src/refractor/visitors/Visitor.ts
packages/apidom-ns-asyncapi-2/test/refractor/elements/Reference/__snapshots__/index.ts.snap
packages/apidom-ns-asyncapi-2/test/refractor/elements/Reference/index.ts

This change is specific to cases when semantic ApiDOM is refractored from generic ApiDOM.
Refs #3842

fix(ns-asyncapi-2): retain meta & attributes during refracting

---

packages/apidom-ns-workflows-1/src/refractor/visitors/Visitor.ts
packages/apidom-ns-workflows-1/test/refractor/elements/Info/__snapshots__/index.ts.snap
packages/apidom-ns-workflows-1/test/refractor/elements/Info/index.ts

This change is specific to cases when semantic ApiDOM is refractoredfrom generic ApiDOM.
Refs #3842

fix(ns-workflow-1): retain meta & attributes during refracting

---

packages/apidom-ns-api-design-systems/test/refractor/plugins/openapi-3-1/__snapshots__/standard-identifier-selectors.ts.snap
packages/apidom-ns-openapi-3-0/src/refractor/visitors/Visitor.ts
packages/apidom-ns-openapi-3-0/test/refractor/elements/Info/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-0/test/refractor/elements/Info/index.ts
packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/callbacks/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/paths/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/web-hooks/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/__snapshots__/index.ts.snap

This change is specific to cases when semantic ApiDOM
is refractored from generic ApiDOM.
Refs #3842

fix(ns-openapi-3-0): retain meta & attributes during refracting

---

packages/apidom-ns-openapi-3-1/test/refractor/elements/Info/__snapshots__/index.ts.snap
packages/apidom-ns-openapi-3-1/test/refractor/elements/Info/index.ts

This change is specific to cases when semantic ApiDOM is refractored from generic ApiDOM.
Refs #3842

fix(ns-openapi-3-1): retain meta & attributes during refracting

---

packages/apidom-ns-api-design-systems/src/refractor/visitors/Visitor.ts
packages/apidom-ns-asyncapi-2/src/refractor/visitors/Visitor.ts
packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/Visitor.ts
packages/apidom-ns-json-schema-draft-4/test/refractor/elements/JSONSchema/__snapshots__/index.ts.snap
packages/apidom-ns-json-schema-draft-4/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-draft-6/test/refractor/elements/JSONSchema/__snapshots__/index.ts.snap
packages/apidom-ns-json-schema-draft-6/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-draft-7/test/refractor/elements/JSONSchema/__snapshots__/index.ts.snap
packages/apidom-ns-json-schema-draft-7/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-openapi-2/src/refractor/visitors/Visitor.ts
packages/apidom-ns-openapi-3-0/src/refractor/visitors/Visitor.ts
packages/apidom-ns-workflows-1/src/refractor/visitors/Visitor.ts

This change is specific to cases when semantic ApiDOM is refractored from generic ApiDOM.
Refs #3842

fix(ns-json-schema): retain meta & attributes during refracting

---

packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/fixtures/external-cycle/ex.json
packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/fixtures/external-cycle/root.json
packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts

fix(reference): add support for external cycles detection in OpenAPI 2.0 dereference strategy

---

packages/@types/minim.d.ts
packages/apidom-core/src/transformers/serializers/value/index.ts
packages/apidom-core/test/transformers/serializers/value.ts
packages/apidom-core/test/traversal/visitor.ts

feat(core): add support for RefElement, LinkElement

---

packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
packages/apidom-reference/src/options/index.ts
packages/apidom-reference/src/resolve/strategies/apidom/index.ts
packages/apidom-reference/src/types.ts

feat(reference): skip processing internal refererences in apidom resolve strategy

---

packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts

feat(reference): add support for skipping internal references in AsyncAPI 2.x dereference strategy

---

packages/apidom-converter/src/errors/ConvertError.ts
packages/apidom-converter/src/index.ts
packages/apidom-converter/test/index.ts

convert and convertApiDOM functions with now always
return ConverError instances on failure.
Refs #3998

feat(converter): create unified error boundary interface

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type.ts
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/__snapshots__/index.ts.snap
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/fixtures/reference-objects.json
packages/apidom-converter/test/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type/index.ts

This change is specific to openapi-3-1-to-openapi-3-0-3 strategy.
Refs #4000

feat(converter): add Reference Object removal support in security-scheme-type plugin

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type.ts
packages/apidom-ls/src/services/validation/validation-service.ts
packages/apidom-reference/src/Reference.ts
packages/apidom-reference/src/ReferenceSet.ts
packages/apidom-reference/src/dereference/strategies/apidom/index.ts
packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
packages/apidom-reference/src/types.ts
packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts

Refs #3481
BREAKING CHANGE: Reference from apidom-reference package became a class and requires to be instantiated with new operator.

feat(reference): change Reference from stamp to TypeScript class

---

packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/refractor-plugins/security-scheme-type.ts
packages/apidom-ls/src/services/validation/validation-service.ts
packages/apidom-reference/src/Reference.ts
packages/apidom-reference/src/ReferenceSet.ts
packages/apidom-reference/src/dereference/strategies/apidom/index.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/index.ts
packages/apidom-reference/src/index.ts
packages/apidom-reference/src/resolve/index.ts
packages/apidom-reference/src/resolve/strategies/apidom/index.ts
packages/apidom-reference/src/resolve/strategies/asyncapi-2/index.ts
packages/apidom-reference/src/resolve/strategies/openapi-2/index.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-0/index.ts
packages/apidom-reference/src/resolve/strategies/openapi-3-1/index.ts
packages/apidom-reference/src/types.ts
packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts

Refs #3481
BREAKING CHANGE: ReferenceSet from apidom-reference package became a class and requires to be instantiated with new operator.

feat(reference): change ReferenceSet from stamp to TypeScript class

---

package-lock.json
packages/apidom-reference/package.json
packages/apidom-reference/src/ReferenceSet.ts
packages/apidom-reference/src/dereference/strategies/apidom/index.ts
packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-2/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/index.ts
packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts

Refs #3481
BREAKING CHANGE: all visitors from apidom-reference package became a class and requires to be instantiated with new operator.

feat(reference): change dereference visitors from stamps to TypeScript classes

---

.github/workflows/release-to-GPR.yml

We want to automatically release ApiDOM npm packages to GitHub Package Registry along with npmj.com.

ci(release): automatically release to GitHub Package Registry

---

packages/apidom-playground/src/playground/apidom.worker.js

This PR fixed an issue when after importing the file content is missing. The only thing that is displayed is the string [object ArrayBuffer].
Locally.
https://github.com/user-attachments/assets/3e130e8b-7b5e-46c4-a7bd-8f605cd3f072

fix(playground): fix importing definition from URL

---

packages/apidom-parser-adapter-openapi-json-3-0/src/adapter.ts
packages/apidom-parser-adapter-openapi-json-3-0/test/adapter.ts

This PR removes rc version support from `apidom-parser-adapter-openapi-json-3-0` package.
This PR does the following:
- modifies version detection RegExp
- adds one additional test to ensure that rc releases are not recognized anymore
Closes https://github.com/swagger-api/apidom/issues/2265
It has been tested by adding new unit tests in the package folder.

fix(apidom-parser-adapter-openapi-json-3-0): remove rc version support

---

package-lock.json
packages/apidom-json-path/package.json
packages/apidom-json-path/src/index.ts
packages/apidom-json-path/src/polyfills.ts

Closes #4379
---
In order to update jsonpath-plus, eliminate security issues around it and keep the minimum supported Node.js version to Node.js 12.20.0, polyfills needed to be introduced.

chore(deps): bump jsonpath-plus from 7.2.0 to 10.0.4

---

packages/apidom-parser-adapter-api-design-systems-yaml/.eslintrc
packages/apidom-parser-adapter-api-design-systems-yaml/package.json
packages/apidom-parser-adapter-api-design-systems-yaml/src/adapter.ts
packages/apidom-parser-adapter-api-design-systems-yaml/test/adapter.ts
packages/apidom-parser-adapter-api-design-systems-yaml/test/media-types.ts
packages/apidom-parser-adapter-api-design-systems-yaml/test/mocha-bootstrap.ts
packages/apidom-parser-adapter-api-design-systems-yaml/test/tsconfig.json
packages/apidom-parser-adapter-api-design-systems-yaml/tsconfig.declaration.json
packages/apidom-parser-adapter-api-design-systems-yaml/tsconfig.json

build(parser-adapter-api-design-systems-yaml): use nodenext for TypeScript modules

---

packages/apidom-parser-adapter-workflows-yaml-1/.eslintrc
packages/apidom-parser-adapter-workflows-yaml-1/package.json
packages/apidom-parser-adapter-workflows-yaml-1/src/adapter.ts
packages/apidom-parser-adapter-workflows-yaml-1/test/adapter.ts
packages/apidom-parser-adapter-workflows-yaml-1/test/media-types.ts
packages/apidom-parser-adapter-workflows-yaml-1/test/mocha-bootstrap.ts
packages/apidom-parser-adapter-workflows-yaml-1/test/tsconfig.json
packages/apidom-parser-adapter-workflows-yaml-1/tsconfig.declaration.json
packages/apidom-parser-adapter-workflows-yaml-1/tsconfig.json

build(parser-adapter-workflows-yaml-1): use nodenext for TypeScript modules

---

packages/apidom-logging/package.json
packages/apidom-parser-adapter-api-design-systems-json/package.json

Some packages were missing inclusion of `*.mjs` or `*.cjs` artifacts into npm dist package.
Refs #4539

fix(parser-apadter-ads): include files needed by main entry point

---

packages/apidom-ns-openapi-3-0/src/media-types.ts
packages/apidom-ns-openapi-3-0/src/refractor/plugins/replace-empty-element.ts
packages/apidom-ns-openapi-3-0/test/refractor/elements/OpenApi3-0/__snapshots__/index.mjs.snap
packages/apidom-ns-openapi-3-0/test/refractor/elements/OpenApi3-0/index.ts
packages/apidom-ns-openapi-3-0/test/refractor/elements/Openapi/__snapshots__/index.mjs.snap
packages/apidom-ns-openapi-3-0/test/refractor/elements/Openapi/index.ts

feat(ns-openapi-3-0): add support for OpenAPI 3.0.4

---

packages/apidom-parser-adapter-openapi-json-3-0/src/adapter.ts
packages/apidom-parser-adapter-openapi-json-3-0/test/adapter.ts
packages/apidom-parser-adapter-openapi-json-3-0/test/fixtures/sample-api.json
packages/apidom-parser-adapter-openapi-json-3-0/test/fixtures/sample-api.yaml
packages/apidom-parser-adapter-openapi-json-3-0/test/media-types.ts
packages/apidom-parser-adapter-openapi-yaml-3-0/src/adapter.ts

feat(parser-adapter-openapi-json-3-0): add support for OpenAPI 3.0.4

---

packages/apidom-parser-adapter-openapi-yaml-3-0/src/adapter.ts
packages/apidom-parser-adapter-openapi-yaml-3-0/test/adapter.ts
packages/apidom-parser-adapter-openapi-yaml-3-0/test/fixtures/sample-api.json
packages/apidom-parser-adapter-openapi-yaml-3-0/test/fixtures/sample-api.yaml
packages/apidom-parser-adapter-openapi-yaml-3-0/test/media-types.ts

feat(parser-adapter-openapi-yaml-3-0): add support for OpenAPI 3.0.4

---

packages/apidom-parser-adapter-openapi-yaml-3-0/README.md
packages/apidom-parser-adapter-openapi-yaml-3-0/test/media-types.ts

docs(parser-adapter-openapi-yaml-3-0): adapt to OpenAPI 3.0.4 support

---

packages/apidom-ns-json-schema-2019-09/test/refractor/__snapshots__/index.mjs.snap
packages/apidom-ns-json-schema-2019-09/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-2020-12/test/refractor/__snapshots__/index.mjs.snap
packages/apidom-ns-json-schema-2020-12/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/SpecificationVisitor.ts
packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/json-schema/index.ts
packages/apidom-ns-json-schema-draft-4/test/refractor/__snapshots__/index.mjs.snap
packages/apidom-ns-json-schema-draft-4/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-draft-6/test/refractor/__snapshots__/index.mjs.snap
packages/apidom-ns-json-schema-draft-6/test/refractor/elements/JSONSchema/index.ts
packages/apidom-ns-json-schema-draft-7/test/refractor/__snapshots__/index.mjs.snap
packages/apidom-ns-json-schema-draft-7/test/refractor/elements/JSONSchema/index.ts

`ParentSchemaAwareVisitor` was used, but the data was never properly passed to it.

fix(ns-json-schema): collect properly metadata for dialect and schema identifiers

---

package-lock.json

Dependabot damaged the package-lock.json file which resulted in failing to release npm package to GitHub Package Registry.

fix: allow release to GitHub Package Registry

---

package.json

root level `version` npm script is run updater dependency update
and before the release commit is created. This gives us chance to
fix the corrupted package-lock.json before commiting the changes.

fix(release): auto-fix package-lock.json after release

---

package-lock.json
packages/apidom-reference/package.json

In https://github.com/swagger-api/apidom/pull/4154 `apidom-error` was added as a direct dependency, but wasn't removed as an optional or dev dependency. Given it is now required directly, let's just drop it from the optional and the dev lists.
﻿### Motivation and Context
Some internal tooling had problems with it, as yarn@1 lockfiles end up in a weird state when a dependency is both required and optional
🤷 
N/A

fix: Remove unnecessary dependency entries
