swagger-api/apidom

- packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-asyncapi-2/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-asyncapi-2/test/refractor/plugins/replace-empty-element/mappings.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/replace-empty-element/mappings.ts
> fix(replace-empty-element): map additional Schema keywords

- NOTICE
> docs(NOTICE): make information about ApiDOM license explicit

- .github/workflows/build.yml
> ci: skip providing GitHub package registry credentials

- package.json
Refs https://github.com/swagger-api/oss-planning/issues/472
> chore(package): add scripts for linking the monorepo

- .github/workflows/build.yml
> revert: ci: skip providing GitHub package registry credentials

- .github/dependabot.yml
> chore(dependabot): issue auto-update PRs at 23:00 UTC

- package-lock.json
> chore(security): update follow-redirects to v1.14.7

- .github/workflows/build.yml
- .husky/commit-msg
- .husky/pre-commit
> ci(build): lint commit messages in PRs only

- packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/message/index.ts
- packages/apidom-ns-asyncapi-2/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-asyncapi-2/test/refractor/plugins/replace-empty-element/mappings.ts
> feat(ns-asyncapi-2): add support for Message.payload empty values

- package-lock.json
- packages/apidom-playground/.eslintrc
- packages/apidom-playground/package.json
- packages/apidom-playground/scripts/build.js
- packages/apidom-playground/scripts/start.js
- packages/apidom-playground/src/index.jsx
- packages/apidom-playground/src/playground/plugin.js
- packages/apidom-playground/src/playground/reducers.js
> build(playground): migrate to CRA5

- .env
- .github/workflows/build.yml
- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
- README.md
- packages/apidom-ast/package.json
- packages/apidom-core/package.json
- packages/apidom-ls/package.json
- packages/apidom-ns-asyncapi-2/package.json
- packages/apidom-ns-openapi-3-1/package.json
- packages/apidom-parser-adapter-asyncapi-json-2/package.json
- packages/apidom-parser-adapter-asyncapi-yaml-2/package.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-openapi-json-3-1/package.json
- packages/apidom-parser-adapter-openapi-yaml-3-1/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
- packages/apidom-parser/package.json
- packages/apidom-reference/package.json
> build: use parallelization depending on CPU cores

- packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/replace-empty-element.ts
> refactor: provide context to replace empty plugins

- package-lock.json
- packages/apidom-playground/package.json
Regeneration allow optimization in dep tree
to kick in and simplify deps structure
within node_modules directory
> chore(package-lock): regenerate from scratch

- babel.config.js
> build(babel): modernize babel config

- .browserslistrc
- babel.config.js
- packages/apidom-ast/package.json
- packages/apidom-core/package.json
- packages/apidom-ls/package.json
- packages/apidom-ns-asyncapi-2/package.json
- packages/apidom-ns-openapi-3-1/package.json
- packages/apidom-parser-adapter-asyncapi-json-2/package.json
- packages/apidom-parser-adapter-asyncapi-yaml-2/package.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-openapi-json-3-1/package.json
- packages/apidom-parser-adapter-openapi-yaml-3-1/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
- packages/apidom-parser/package.json
- packages/apidom-reference/package.json
IE 11 was explicitly excluded.
> build(browserlist): use explicit browserlist

- babel.config.cjs
> build(babel): remove reference to babel-plugin-add-import-extension

- package-lock.json
- packages/apidom-ns-api-design-systems/package.json
- packages/apidom-ns-api-design-systems/src/adapters/json.ts
- packages/apidom-ns-api-design-systems/src/adapters/yaml.ts
> feat(ns-api-design-systems): introduce adapters

- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/components-correlation-ids/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/components-correlation-ids/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/message-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/message-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/message-trait-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/fixtures/message-trait-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/correlation-id-object/index.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/components-message-bindings/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/components-message-bindings/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/message-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/message-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/message-trait-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/fixtures/message-trait-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-bindings-object/index.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-trait-object/fixtures/components-message-traits/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-trait-object/fixtures/components-message-traits/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-trait-object/fixtures/message-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-trait-object/fixtures/message-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/message-trait-object/index.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/security-scheme-object/fixtures/components-security-schemes/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/security-scheme-object/fixtures/components-security-schemes/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/security-scheme-object/index.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-bindings-object/fixtures/components-server-bindings/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-bindings-object/fixtures/components-server-bindings/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-bindings-object/fixtures/server-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-bindings-object/fixtures/server-object/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-bindings-object/index.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-object/fixtures/components-servers/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-object/fixtures/components-servers/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/server-object/index.ts
> Asyncapi dereference tests

- package-lock.json
Refs https://github.com/swagger-api/apidom/security/dependabot/11
> chore(deps): fix security issue with minimist

- package-lock.json
- packages/apidom-playground/package.json
- packages/apidom-playground/scripts/build.js
- packages/apidom-playground/scripts/start.js
Closes #1323
Refs https://github.com/swagger-api/oss-planning/issues/557
> chore(deps-dev): bump react-scripts from 5.0.0 to 5.0.1

- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/pets/def.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/pets/def2.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/pets/def3.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/pets/pets.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/pets/response.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/fixtures/document-boundaries/root.yml
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/index.ts
This enhancement is specific to crossing document boundaries
in different contexts.
Closes #1337
> fix(reference): enhance OpenAPI 3.1 resolution

- packages/apidom-ls/src/config/asyncapi/message/complete/message.ts
- packages/apidom-ls/src/config/asyncapi/operation/lint/message.ts
- packages/apidom-ns-asyncapi-2/src/elements/nces/OperationMessageMap.ts
- packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/operation/MessageVisitor.ts
> feat(apidom-ls): support oneOf field in Operation.message field

- packages/apidom-parser-adapter-asyncapi-json-2/README.md
- packages/apidom-parser-adapter-asyncapi-yaml-2/README.md
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/fixtures/sample-api.yaml
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/perf/fixtures/asyncapi.yaml
- packages/apidom-parser/README.md
> refactor: reference AsyncAPI 2.4 spec primarily

- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/operation/MessageVisitor.ts
- packages/apidom-ns-asyncapi-2/test/refractor/__snapshots__/index.ts.snap
- packages/apidom-ns-asyncapi-2/test/refractor/fixtures/asyncapi-2-4-0.json
oneOf field can be defined as an Operation.message
value.
Closes #1348
> fix(ns-asyncapi-2): provide semantics for oneOf field

- package-lock.json
- package.json
- packages/apidom-json-path/test/index.ts
- packages/apidom-json-pointer/.eslintignore
- packages/apidom-json-pointer/.gitignore
- packages/apidom-json-pointer/.mocharc.json
- packages/apidom-json-pointer/.npmrc
- packages/apidom-json-pointer/README.md
- packages/apidom-json-pointer/config/rollup/types.dist.js
- packages/apidom-json-pointer/config/webpack/browser.config.js
- packages/apidom-json-pointer/config/webpack/traits.config.js
- packages/apidom-json-pointer/declaration.tsconfig.json
- packages/apidom-json-pointer/package.json
- packages/apidom-json-pointer/src/errors/EvaluationJsonPointerError.ts
- packages/apidom-json-pointer/src/errors/InvalidJsonPointerError.ts
- packages/apidom-json-pointer/src/errors/index.ts
- packages/apidom-json-pointer/src/index.ts
- packages/apidom-json-pointer/test/.eslintrc
- packages/apidom-json-pointer/test/index.ts
- packages/apidom-json-pointer/test/mocha-bootstrap.cjs
- packages/apidom-json-pointer/tsconfig.json
> feat(json-pointer): add support for JSON Pointer

- package-lock.json
- packages/apidom-json-path/package.json
- packages/apidom-json-path/src/index.ts
- packages/apidom-json-path/test/index.ts
> feat(json-path): add support for JSONPath

- packages/apidom-ns-openapi-3-1/src/elements/Link.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/__snapshots__/index.ts.snap
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/components-links/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/operation-id/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/operation-ref-external/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/operation-ref-internal/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/fixtures/response-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/index.ts
- packages/apidom-reference/test/mocha-bootstrap.cjs
This change is specific to OpenAPI 3.1 spec.
Refs #1483
> refactor(reference): dereference Operation into meta

- packages/apidom-ls/src/apidom-language-types.ts
- packages/apidom-ls/src/services/completion/completion-service.ts
- packages/apidom-ls/test/completion-provider.ts
> feat(apidom-ls): allow async doRefCompletion (#1512)

- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/message/index.ts
- packages/apidom-ns-asyncapi-2/test/refractor/elements/Message/__snapshots__/index.ts.snap
- packages/apidom-ns-asyncapi-2/test/refractor/elements/Message/index.ts
> fix(ns-asyncapi-2): fix refracting of Message.payload

- packages/apidom-parser-adapter-asyncapi-json-2/src/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/src/adapter.ts
- packages/apidom-parser-adapter-json/src/adapter.ts
- packages/apidom-parser-adapter-openapi-json-3-1/src/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-1/src/adapter.ts
> fix(OpenAPI): detect OpenAPI in different formats properly

- packages/apidom-ns-api-design-systems/package.json
- packages/apidom-ns-api-design-systems/src/adapters/json/adapter.ts
- packages/apidom-ns-api-design-systems/src/adapters/json/media-types.ts
- packages/apidom-ns-api-design-systems/src/adapters/yaml/adapter.ts
- packages/apidom-ns-api-design-systems/src/adapters/yaml/media-types.ts
- packages/apidom-ns-api-design-systems/test/adapters/json.ts
- packages/apidom-ns-api-design-systems/test/adapters/yaml.ts
> feat(api-design-systems): add better JSON & YAML detection

- packages/apidom-parser-adapter-asyncapi-json-2/src/adapter.ts
- packages/apidom-parser-adapter-asyncapi-json-2/test/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/src/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/adapter.ts
- packages/apidom-parser-adapter-openapi-json-3-1/src/adapter.ts
- packages/apidom-parser-adapter-openapi-json-3-1/test/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-1/src/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-1/test/adapter.ts
> Specification detection enhancements

- packages/apidom-parser-adapter-asyncapi-json-2/src/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/src/adapter.ts
- packages/apidom-parser-adapter-openapi-json-3-1/src/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-1/src/adapter.ts
> Export detection regular expressions

- packages/apidom-ns-api-design-systems/src/adapters/json/adapter.ts
- packages/apidom-ns-api-design-systems/src/adapters/yaml/adapter.ts
> feat(ns-api-design-systems): export detection regexp

- packages/apidom-ns-api-design-systems/src/media-types.ts
- packages/apidom-ns-asyncapi-2/src/media-types.ts
- packages/apidom-ns-openapi-3-1/src/media-types.ts
- packages/apidom-parser-adapter-asyncapi-json-2/README.md
- packages/apidom-parser-adapter-asyncapi-yaml-2/README.md
- packages/apidom-parser-adapter-json/README.md
- packages/apidom-parser-adapter-openapi-json-3-1/README.md
- packages/apidom-parser-adapter-openapi-yaml-3-1/README.md
- packages/apidom-parser-adapter-yaml-1-2/README.md
> Fix `latest` getter on mediaTypes lists

- packages/apidom-parser-adapter-json/src/adapter-node.ts
- packages/apidom-parser-adapter-json/src/adapter.ts
- packages/apidom-parser-adapter-json/test/adapter-node.ts
This new detection eliminates some really nonsensical
cases.
> feat(parser-adapter-json): enhance JSON detection

- packages/apidom-ls/src/apidom-language-service.ts
- packages/apidom-ls/src/index.ts
- packages/apidom-ls/src/parser-factory.ts
- packages/apidom-ls/src/services/completion/completion-service.ts
- packages/apidom-ls/src/services/deref/deref-service.ts
- packages/apidom-ls/src/services/hover/hover-service.ts
- packages/apidom-ls/src/services/semantic-tokens/semantic-tokens-service.ts
- packages/apidom-ls/src/services/validation/providers/json-schema-validation-provider.ts
- packages/apidom-ls/src/services/validation/validation-service.ts
- packages/apidom-ls/src/utils/utils.ts
- packages/apidom-ls/test/asyncapi-json.ts
- packages/apidom-ls/test/completion-provider.ts
- packages/apidom-ls/test/detect.ts
- packages/apidom-ls/test/fixtures/syntax/sample-api-no-version.json
- packages/apidom-ls/test/fixtures/syntax/sample-api-noquotes-sort.yaml
- packages/apidom-ls/test/fixtures/syntax/sample-api-noquotes.yaml
- packages/apidom-ls/test/fixtures/syntax/sample-api-upper.json
- packages/apidom-ls/test/fixtures/syntax/sample-api.json
- packages/apidom-ls/test/fixtures/syntax/sample-api.yaml
- packages/apidom-ls/test/openapi-json.ts
- packages/apidom-ls/test/openapi-jsonschema.ts
- packages/apidom-ls/test/openapi-yaml.ts
> feat(apidom-ls): use adapter.detect for ns/format detection

- packages/apidom-parser-adapter-json/test/adapter-node.ts
- packages/apidom-reference/src/dereference/index.ts
- packages/apidom-reference/src/parse/index.ts
- packages/apidom-reference/src/parse/parsers/Parser.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-api-design-systems-json/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-api-design-systems-yaml/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-asyncapi-json-2/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-asyncapi-yaml-2/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-binary/index-browser.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-binary/index-node.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-json/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-openapi-json-3-1/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-openapi-yaml-3-1/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-reference-parser-yaml-1-2/index.ts
- packages/apidom-reference/src/resolve/index.ts
- packages/apidom-reference/src/resolve/util.ts
- packages/apidom-reference/src/types.ts
- packages/apidom-reference/src/util/plugins.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-api-design-systems-json/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-api-design-systems-yaml/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-asyncapi-json-2/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-asyncapi-yaml-2/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-binary/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-json/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-openapi-json-3-1/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-openapi-yaml-3-1/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-reference-parser-yaml/index.ts
- packages/apidom-reference/test/util/plugins.ts
> feat(reference): use smart spec/format detection with parser plugins

- packages/apidom-ast/src/yaml/schemas/canonical-format.ts
> fix(ast): minic lookbehind regexp to support Safari

- packages/apidom-reference/package.json
- packages/apidom-reference/src/dereference/index.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/src/index.ts
- packages/apidom-reference/src/parse/index.ts
- packages/apidom-reference/src/resolve/index.ts
- packages/apidom-reference/src/resolve/resolvers/FileResolver/index-node.ts
- packages/apidom-reference/src/resolve/resolvers/HttpResolver.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/util.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/src/util/File.ts
- packages/apidom-reference/src/util/url.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/path-encoding/path with spaces/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/path-encoding/path with spaces/ex1.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/path-encoding/path with spaces/ex2.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/path-encoding/path with spaces/ex3.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/path-encoding/path with spaces/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/path-encoding/path with spaces/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/path-encoding/path with spaces/ex1.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/path-encoding/path with spaces/ex2.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/path-encoding/path with spaces/ex3.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/path-encoding/path with spaces/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
- packages/apidom-reference/test/resolve/strategies/openapi-3-1/schema-object/index.ts
- packages/apidom-reference/test/util/url.ts
> fix(reference): fix encoding problem with file system paths

- packages/apidom-ns-json-schema-draft-4/README.md
- packages/apidom-ns-json-schema-draft-4/src/elements/JSONSchema.ts
- packages/apidom-ns-json-schema-draft-4/src/elements/LinkDescription.ts
- packages/apidom-ns-json-schema-draft-4/src/elements/Media.ts
- packages/apidom-ns-json-schema-draft-4/src/refractor/specification.ts
- packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/json-schema/BaseVisitor.ts
- packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/json-schema/FragmentResolutionVisitor.ts
- packages/apidom-ns-json-schema-draft-4/test/refractor/__snapshots__/index.ts.snap
- packages/apidom-ns-json-schema-draft-4/test/refractor/elements/JSONSchema/__snapshots__/index.ts.snap
- packages/apidom-ns-json-schema-draft-4/test/refractor/elements/JSONSchema/index.ts
- packages/apidom-ns-json-schema-draft-4/test/refractor/fixtures/json-schema-draft4.json
> feat(ns-json-schema-draft-4): incorporate JSON Schema Draft 5

- packages/apidom-ns-json-schema-draft-4/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-json-schema-draft-4/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-json-schema-draft-4/test/refractor/plugins/replace-empty-element/mappings.ts
- packages/apidom-ns-json-schema-draft-6/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-json-schema-draft-6/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-json-schema-draft-6/test/refractor/plugins/replace-empty-element/mappings.ts
> Complete replace element refractor plugin for JSON Schema namespaces

- packages/apidom-ns-json-schema-draft-4/src/media-types.ts
- packages/apidom-ns-json-schema-draft-6/src/media-types.ts
- packages/apidom-ns-json-schema-draft-7/src/media-types.ts
> fix(json-schema): fix media type versions

- package-lock.json
- packages/apidom-ns-openapi-3-0/.eslintignore
- packages/apidom-ns-openapi-3-0/.gitignore
- packages/apidom-ns-openapi-3-0/.mocharc.json
- packages/apidom-ns-openapi-3-0/.npmrc
- packages/apidom-ns-openapi-3-0/README.md
- packages/apidom-ns-openapi-3-0/config/rollup/types.dist.js
- packages/apidom-ns-openapi-3-0/config/webpack/browser.config.js
- packages/apidom-ns-openapi-3-0/config/webpack/traits.config.js
- packages/apidom-ns-openapi-3-0/declaration.tsconfig.json
- packages/apidom-ns-openapi-3-0/package.json
- packages/apidom-ns-openapi-3-0/src/index.ts
- packages/apidom-ns-openapi-3-0/test/.eslintrc
- packages/apidom-ns-openapi-3-0/test/mocha-bootstrap.cjs
- packages/apidom-ns-openapi-3-0/tsconfig.json
> chore: add scaffolded OpenAPI 3.0 namespace package

- packages/apidom-ns-openapi-3-1/config/webpack/browser.config.js
> fix(build): fix entry point file

- package-lock.json
- packages/apidom-ns-openapi-3-0/package.json
> chore(deps): fix packages topology

- packages/apidom-ns-json-schema-draft-4/src/elements/JSONSchema.ts
- packages/apidom-ns-openapi-3-0/src/elements/Schema.ts
> feat(ns-openapi-3-0): implement Schema element

- packages/apidom-ns-openapi-3-0/src/index.ts
- packages/apidom-ns-openapi-3-0/src/media-types.ts
- packages/apidom-ns-openapi-3-0/src/namespace.ts
- packages/apidom-ns-openapi-3-0/src/predicates.ts
- packages/apidom-ns-openapi-3-0/src/traversal/visitor.ts
- namespace
- media types
- predicates
- traversal
- entry point
Refs #1888
> feat(ns-openapi-3-0): feat add supporting code

- .github/workflows/build.yml
- package-lock.json
- package.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
> chore(deps-dev): bump tree-sitter-cli from 0.20.6 to 0.20.7

- packages/apidom-ls/src/config/openapi/header/documentation.ts
Cleanup comments from #2000.
Missed a pass to cleanup comments. Whoops.
> chore(ls): cleanup oas31 docs for header object

- packages/apidom-ls/src/config/openapi/header/documentation.ts
Add targetSpecs oas3.1
followup to #2000
> fix(ls): add targetSpecs for header object

- packages/apidom-ls/src/config/openapi/oauth-flow/documentation.ts
Change heading format from `h4` to smaller `h5`.
Visual style improvement, and consistency with #2018 implementation
local.
> refactor(ls): oas31 docs update formatting for oauth-flow

- packages/apidom-ls/src/config/openapi/config.ts
- packages/apidom-ls/src/config/openapi/xml/documentation.ts
- packages/apidom-ls/src/config/openapi/xml/meta.ts
Add documentation for OpenAPI 3.1.0 XML object.
Also add custom section for `Additional documentation topics` that provide external links for further reading.
Ref: #2024 
local.
fixture:
```yaml
openapi: 3.1.0
info:
title: deref
version: 1.0.0
components:
schemas:
Message: 
type: object
xml: 
name: MESSAGE
properties:
att1:
type: string
example: Name
xml:
attribute: true
att2:
type: string
example: DOB
xml:
attribute: true 
```
parent 1:
parent 2, with `Additional documentation topics`:
target 1, `name`:
target 2, `attribute`:
> feat(ls): docs for OpenApi 3.1.0 XML object

- packages/apidom-ls/src/config/common/schema/completion.ts
- packages/apidom-ls/src/config/common/schema/documentation.ts
- packages/apidom-ls/src/config/common/schema/lint/discriminator--type-asyncapi-2-0--2-4.ts
- packages/apidom-ls/src/config/common/schema/lint/index.ts
> refactor(ls): amend discriminator rules, allow OpenAPI 3.1 to plug in

- packages/apidom-ls/src/config/openapi/components/documentation.ts
> feat(ls): provide OpenAPI 3.0.x Components docs rules

- packages/apidom-ls/src/config/openapi/config.ts
- packages/apidom-ls/src/config/openapi/openapi3_0/documentation.ts
- packages/apidom-ls/src/config/openapi/openapi3_0/meta.ts
- packages/apidom-ls/src/config/openapi/openapi3_1/documentation.ts
> feat(ls): provide OpenAPI 3.0.x OpenAPI docs rules

- packages/apidom-ls/src/config/openapi/components/completion.ts
- packages/apidom-ls/src/config/openapi/components/documentation.ts
- packages/apidom-ls/src/config/openapi/components/meta.ts
- packages/apidom-ls/src/config/openapi/external-documentation/completion.ts
- packages/apidom-ls/src/config/openapi/external-documentation/meta.ts
- packages/apidom-ls/src/config/openapi/info/completion.ts
- packages/apidom-ls/src/config/openapi/license/completion.ts
- packages/apidom-ls/src/config/openapi/license/meta.ts
- packages/apidom-ls/src/config/openapi/openapi3_0/completion.ts
- packages/apidom-ls/src/config/openapi/openapi3_0/meta.ts
- packages/apidom-ls/src/parser-factory.ts
- packages/apidom-ls/test/openapi-yaml.ts
Includes following specifications objects:
- OpenAPI
- Info
- Contact
- License
- Components 
- External Documentation
Refs https://github.com/swagger-api/apidom/issues/2032
> OpenAPI 3.0.x language server completion rules

- packages/apidom-ls/src/config/openapi/server-variable/documentation.ts
> feat(ls): provide OpenAPI 3.0.x Server Variable docs rules

- packages/apidom-ls/package.json
Add dev dependency to `apidom-ls` package: `@swagger-api/apidom-ns-openapi-3-0`
otherwise failure to build locally on MacOs
local build now works
> chore(ls-deps): add apidom-ns-openapi-3-0

- package-lock.json
- packages/apidom-playground/package.json
- packages/apidom-reference/package.json
- axios from 0.27.2 to 1.0.0
- sass from 1.54.5 to 1.55.0
- web-vitals from 3.0.0 to 3.0.2
Closes #2096
Closes #2098
Closes #2107
> chore(deps): bump several deps to latest versions

- packages/apidom-ls/src/config/openapi/example/lint/value--mutually-exclusive.ts
> fix(ls): fix OpenAPI 3.x.y Example Obj mutually exclusive lint rule

- packages/apidom-ls/src/config/openapi/server/completion.ts
Refs ae9ec4f89a5e2afacc64575ef7151ad0ee38d404
> fix(ls): finalize rules for OpenAPI Server object

- packages/apidom-ls/src/config/openapi/xml/completion.ts
provide OpenAPI 3.1.0 completion rules for XML object
Ref: #2062 
Ref: #2061 (no update needed)
> feat(ls): provide OpenAPI 3.1.0 completion rules for XML object

- packages/apidom-ls/src/config/openapi/encoding/completion.ts
Refs a4618af698b668c925d00d9fc223095f05518f34
Refs #2032
> feat(ls): add completion rules for Encoding.style field

- packages/apidom-ls/src/config/openapi/link/completion.ts
Refs beb02b9da9f004383a6fc053aa1e6e6bed3fe000
Refs #2206
> fix(ls): fix OpenAPI Link.requestBody field completion

- packages/apidom-ls/src/config/openapi/example/lint/allowed-fields-3-1.ts
- packages/apidom-ls/src/config/openapi/example/lint/index.ts
> feat(ls): provide OpenAPI 3.1.0 Example allowed fields link rule

- packages/apidom-ls/src/config/openapi/parameter/documentation.ts
> fix(ls): fix docs rule for OpenAPI 3.x.y Parameter

- packages/apidom-ls/src/config/openapi/response/lint/allowed-fields-3-1.ts
- packages/apidom-ls/src/config/openapi/response/lint/index.ts
> feat(ls): provide OpenAPI 3.1 Response allowed fields link rule

- packages/apidom-ls/src/config/openapi/responses/documentation.ts
> feat(ls): provide OpenAPI 3.1 Responses docs rules

- packages/apidom-ns-asyncapi-2/src/elements/ChannelItem.ts
- packages/apidom-ns-asyncapi-2/src/elements/Contact.ts
- packages/apidom-ns-asyncapi-2/src/elements/CorrelationID.ts
- packages/apidom-ns-asyncapi-2/src/elements/ExternalDocumentation.ts
- packages/apidom-ns-asyncapi-2/src/elements/Info.ts
- packages/apidom-ns-asyncapi-2/src/elements/License.ts
- packages/apidom-ns-asyncapi-2/src/elements/MessageExample.ts
- packages/apidom-ns-asyncapi-2/src/elements/MessageTrait.ts
- packages/apidom-ns-asyncapi-2/src/elements/OAuthFlow.ts
- packages/apidom-ns-asyncapi-2/src/elements/OAuthFlows.ts
- packages/apidom-ns-asyncapi-2/src/elements/Operation.ts
- packages/apidom-ns-asyncapi-2/src/elements/OperationTrait.ts
- packages/apidom-ns-asyncapi-2/src/elements/Parameter.ts
- packages/apidom-ns-asyncapi-2/src/elements/Reference.ts
- packages/apidom-ns-asyncapi-2/src/elements/SecurityScheme.ts
- packages/apidom-ns-asyncapi-2/src/elements/Server.ts
- packages/apidom-ns-asyncapi-2/src/elements/ServerVariable.ts
- packages/apidom-ns-asyncapi-2/src/elements/Tag.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
> feat(ns-asyncapi-2): improve types for elements

- packages/apidom-ns-asyncapi-2/src/elements/ChannelBindings.ts
- packages/apidom-ns-asyncapi-2/src/elements/MessageBindings.ts
- packages/apidom-ns-asyncapi-2/src/elements/OperationBindings.ts
- packages/apidom-ns-asyncapi-2/src/elements/Server.ts
- packages/apidom-ns-asyncapi-2/src/elements/ServerBindings.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/googlepubsub/GooglePubSubChannelBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/googlepubsub/GooglePubSubMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/googlepubsub/GooglePubSubOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/googlepubsub/GooglePubSubServerBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/ibmmq/IbmmqOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/index.ts
- packages/apidom-ns-asyncapi-2/src/namespace.ts
> feat(ns-asyncapi-2): add support for 2.5.0 version in element layer

- packages/apidom-ns-asyncapi-2/src/elements/Message.ts
- packages/apidom-ns-asyncapi-2/src/elements/Parameter.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/amqp/AmqpChannelBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/amqp/AmqpMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/amqp/AmqpOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/anypointmq/AnypointmqChannelBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/anypointmq/AnypointmqMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/http/HttpMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/http/HttpOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/ibmmq/IbmmqChannelBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/ibmmq/IbmmqMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/ibmmq/IbmmqServerBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/kafka/KafkaMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/kafka/KafkaOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/mqtt/MqttMessageBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/mqtt/MqttOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/mqtt/MqttServerBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/solace/SolaceOperationBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/solace/SolaceServerBinding.ts
- packages/apidom-ns-asyncapi-2/src/elements/bindings/ws/WebSocketChannelBinding.ts
> feat(ns-asyncapi-2): improve types for bindings elements

- packages/apidom-ls/src/config/asyncapi/server/lint/allowed-fields-2-0--2-4.ts
- packages/apidom-ls/src/config/asyncapi/server/lint/allowed-fields-2-5.ts
- packages/apidom-ls/src/config/asyncapi/server/lint/index.ts
> fix(ls): fix lint rule for AsyncAPI 2.5.0 Server.tags

- package-lock.json
- package.json
> chore(deps-dev): bump typescript from 4.8.4 to 4.9.3

- package-lock.json
- packages/apidom-reference/README.md
- packages/apidom-reference/package.json
- packages/apidom-reference/src/index.ts
- packages/apidom-reference/src/resolve/resolvers/HttpResolverAxios.ts
- packages/apidom-reference/src/resolve/resolvers/HttpResolverSwaggerClient.ts
- packages/apidom-reference/test/resolve/resolvers/HttpResolverAxios.ts
- packages/apidom-reference/test/resolve/resolvers/HttpResolverSwaggerClient.ts
> feat(reference): add SwaggerClient's HTTP Client resolver plugin

- packages/apidom-reference/src/dereference/strategies/openapi-3-1-swagger-client/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1-swagger-client/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/helpers/parsers/json/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1-swagger-client/helpers/parsers/openapi-json-3-1/index.ts
This plugin mimics the YAML parsing mechanism from swagger-client.
Refs #2322
> test(reference): add swagger-client OpenAPI 3.1 YAML parser plugin

- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameters.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/callbacks/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/callbacks/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/components/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/components/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/paths/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/paths/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/web-hooks/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/web-hooks/index.ts
> feat(ns-openapi-3-1): add parameters normalization refractor plugin

- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameters.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-security-requirements.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/callbacks/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/callbacks/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/components/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/components/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/paths/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/paths/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/webhooks/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-security-requirements/webhooks/index.ts
> feat(ns-openapi-3-1): add security normalization refractor plugin

- packages/apidom-core/test/serializers/value.ts
- packages/apidom-ls/test/validate-valid.ts
- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-operation-ids.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/index.ts
> feat(ns-openapi-3-1): add operationId normalization refractor plugin

- packages/apidom-reference/src/index.ts
> feat(reference): expose HTTPResolver symbol as public API

- packages/apidom-reference/src/index.ts
> feat(reference): expose File symbol as public API

- packages/apidom-reference/package.json
> feat(reference): export types for subpath exports in package.json

- packages/apidom-reference/package.json
> fix(reference): fix values of sideEffects fields of package.json

- packages/apidom-reference/package.json
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/$anchor/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/uri/index.ts
> feat(reference): expose new symbols to compose dereference strategies

- packages/apidom-core/src/index.ts
- packages/apidom-core/src/refractor/index.ts
- packages/apidom-core/src/refractor/plugins/utils/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/index.ts
- packages/apidom-ns-asyncapi-2/src/refractor/index.ts
- packages/apidom-ns-json-schema-draft-4/src/refractor/index.ts
- packages/apidom-ns-json-schema-draft-6/src/refractor/index.ts
- packages/apidom-ns-json-schema-draft-7/src/refractor/index.ts
- packages/apidom-ns-openapi-3-0/src/refractor/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/index.ts
New dispatcher was used in every namespace package.
Refs #2362
> feat(core): expose refractor plugins dispatcher as public API

- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameter-examples.ts
- packages/apidom-ns-openapi-3-1/src/refractor/toolbox.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameter-examples/components/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameter-examples/paths/index.ts
> feat(ns-openapi-3-1): add Parameter.example(s) normalization refractor plugin

- packages/apidom-ns-openapi-3-0/src/elements/Header.ts
- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-header-examples.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-header-examples/components/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-header-examples/paths/index.ts
> feat(ns-openapi-3-1): add Header.example(s) normalization refractor plugin

- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameter-examples/paths/index.ts
> feat(ns-openapi-3-1): expose creatToolbox as public API

- packages/apidom-json-pointer/src/index.ts
- packages/apidom-json-pointer/test/index.ts
Refs https://www.rfc-editor.org/rfc/rfc6901#section-5
> fix(json-pointer): fix JSON Pointer evaluation for % character

- NOTICE
- packages/@types/minim.d.ts
- packages/apidom-core/README.md
- packages/apidom-core/src/deepmerge.ts
- packages/apidom-core/src/index.ts
- packages/apidom-core/test/deepmerge.ts
This is option-less version of npm package deepmerge that supports deep merging of ApiDOM structures.
> feat(core): addd support for deep merge algorithm

- NOTICE
- packages/apidom-core/README.md
- packages/apidom-core/src/deepmerge.ts
- packages/apidom-core/test/deepmerge.ts
`deepmerge.all` util was added as well.
> feat(core): add options support for deepmerge function

- packages/apidom-parser-adapter-json/src/adapter.ts
One of the main issues was inefficient regular expression detected by CodeQL.
Refs #2503
> fix(parser-adapter-json): fix issues in JSON detection regexp

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
URI reference, may or may not have JSON Pointer
as part of URI reference. This commit takes that
into account and amend error messages appropriately.
> refactor(reference): amend error messages for recursive references

- Dockerfile
- README.md
- docker-compose.yml
This containerized dev setup is provided via docker.
Refs #2514
> build: add support for containerized dev setup

- README.md
- docker-compose.yml
> build(docker): simplify containerized dev setup

- package-lock.json
- packages/apidom-ns-workflows-1/.eslintignore
- packages/apidom-ns-workflows-1/.gitignore
- packages/apidom-ns-workflows-1/.mocharc.json
- packages/apidom-ns-workflows-1/.npmrc
- packages/apidom-ns-workflows-1/README.md
- packages/apidom-ns-workflows-1/config/rollup/types.dist.js
- packages/apidom-ns-workflows-1/config/webpack/browser.config.js
- packages/apidom-ns-workflows-1/config/webpack/traits.config.js
- packages/apidom-ns-workflows-1/declaration.tsconfig.json
- packages/apidom-ns-workflows-1/package.json
- packages/apidom-ns-workflows-1/src/index.ts
- packages/apidom-ns-workflows-1/test/.eslintrc
- packages/apidom-ns-workflows-1/test/index.ts
- packages/apidom-ns-workflows-1/test/mocha-bootstrap.cjs
- packages/apidom-ns-workflows-1/tsconfig.json
> chore: scaffold namespace package for Workflows Specification 1.0.0

- packages/apidom-parser-adapter-asyncapi-json-2/README.md
- packages/apidom-parser-adapter-asyncapi-json-2/test/adapter.ts
- packages/apidom-parser-adapter-asyncapi-json-2/test/fixtures/sample-api.json
- packages/apidom-parser-adapter-asyncapi-json-2/test/fixtures/sample-api.yaml
- packages/apidom-parser-adapter-asyncapi-json-2/test/media-types.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/README.md
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/adapter.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/fixtures/sample-api.json
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/fixtures/sample-api.yaml
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/media-types.ts
- packages/apidom-parser-adapter-asyncapi-yaml-2/test/perf/fixtures/asyncapi.yaml
- packages/apidom-parser-adapter-openapi-json-3-0/test/adapter.ts
- packages/apidom-parser-adapter-openapi-json-3-1/test/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-0/test/adapter.ts
- packages/apidom-parser-adapter-openapi-yaml-3-1/test/adapter.ts
- packages/apidom-parser/README.md
- packages/apidom-parser/test/adapter-priority.ts
> feat(parser-adaptes): add support for AsyncAPI 2.6.0

- packages/apidom-reference/src/util/errors/CausedError.ts
- packages/apidom-reference/src/util/errors/DereferenceError.ts
- packages/apidom-reference/src/util/errors/InvalidSelectorError.ts
- packages/apidom-reference/src/util/errors/NotImplementedError.ts
- packages/apidom-reference/src/util/errors/ParserError.ts
- packages/apidom-reference/src/util/errors/PluginError.ts
- packages/apidom-reference/src/util/errors/ResolverError.ts
CausedError was introduced as backward
compatible base error.
Refs #2561
> fix(reference): fix extension of native errors

- packages/apidom-ls/src/config/openapi/header/lint/required-fields.ts
> fix(ls): fix OpenAPI Header Object required fields lint

- packages/apidom-core/src/serializers/yaml-1-2.ts
- packages/apidom-core/test/serializers/yaml1-2.ts
- packages/apidom-ls/test/openapi-json.ts
- eliminate redundant new lines
- make YAML directive configurable
- make indent char configurable
> fix(core): fix issues in YAML 1.2 serialization

- .github/dependabot.yml
- .github/workflows/build.yml
- package-lock.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
- tree-sitter-cli from 0.20.8 to 0.20.7
- web-tree-sitter from 0.20.8 to 0.20.7
> chore(deps): downgrade tree-sitter related libs

- .github/workflows/nightly-build.yml
- .github/workflows/release.yml
> ci(setup-node): use build-in npm cache

- packages/apidom-ls/package.json
- packages/apidom-ls/src/index.ts
> feat(apidom-ls): update exports for JSON Schema validators

- lerna.json
- package-lock.json
- package.json
> chore(deps-dev): bump lerna from 6.6.2 to 7.0.1

- .github/dependabot.yml
> ci(dependabot): auto update GitHub Actions

- .github/dependabot.yml
Refs https://github.com/swagger-api/apidom/issues/2598
> ci(dependabot): unignore tree-sitter auto-updates

- packages/apidom-ns-openapi-3-0/README.md
This PR corrects the specification supported that's written in the README
> docs(ns-openapi-3-0): Correct specification in intro of README

- package-lock.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
> chore(deps): update tree-sitter to v0.20.4

- packages/apidom-parser-adapter-json/src/syntactic-analysis/direct/index.ts
- packages/apidom-parser-adapter-json/src/syntactic-analysis/direct/visitors/CstVisitor.ts
- packages/apidom-parser-adapter-json/src/syntactic-analysis/indirect/index.ts
- packages/apidom-parser-adapter-json/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
- packages/apidom-parser-adapter-json/test/perf/parse-syntactic-analysis-indirect.cjs
> perf(parser-adapter-json): use tree-sitter cursor for CST traversal

- packages/apidom-parser-adapter-json/src/syntactic-analysis/direct/visitors/CstVisitor.ts
- packages/apidom-parser-adapter-json/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
- packages/apidom-parser-adapter-json/test/adapter-node.ts
- packages/apidom-parser-adapter-json/test/perf/parse-syntactic-analysis-direct.cjs
- packages/apidom-parser-adapter-json/test/perf/parse-syntactic-analysis-indirect.cjs
> fix(parser-adapter-json): construct proper JavaScript string value

- .github/dependabot.yml
- package-lock.json
- package.json
- packages/apidom-reference/src/util/errors/CausedError.ts
- packages/apidom-reference/src/util/errors/DereferenceError.ts
- packages/apidom-reference/src/util/errors/InvalidSelectorError.ts
- packages/apidom-reference/src/util/errors/NotImplementedError.ts
- packages/apidom-reference/src/util/errors/ParserError.ts
- packages/apidom-reference/src/util/errors/PluginError.ts
- packages/apidom-reference/src/util/errors/ResolverError.ts
Refs 19171aa
Refs https://github.com/niksy/babel-plugin-native-error-extend/issues/4
> revert: use babel plugin to capture error causes

- packages/apidom-ns-openapi-3-0/src/refractor/specification.ts
- packages/apidom-ns-openapi-3-0/src/refractor/visitors/open-api-3-0/schema/DefinitionsVisitor.ts
- packages/apidom-ns-openapi-3-0/test/refractor/elements/Schema/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-0/test/refractor/elements/Schema/index.ts
> fix(ns-openapi-3-0): provide missing reference metadata

- packages/apidom-error/README.md
> docs(README): recommend extending ApiDOMStructuredError

- package-lock.json
- packages/apidom-ast/package.json
- packages/apidom-ast/src/traversal/visitor.ts
- packages/apidom-ast/src/yaml/schemas/failsafe/index.ts
> refactor(ast): use apidom-error package

- package-lock.json
- packages/apidom-core/package.json
- packages/apidom-core/src/deepmerge.ts
- packages/apidom-core/src/media-types.ts
> refactor(core): use apidom-error package

- packages/apidom-error/README.md
- packages/apidom-error/src/NotImplementedError.ts
- packages/apidom-error/src/UnsupportedOperationError.ts
- packages/apidom-error/src/index.ts
> feat(error): introduce generic custom errors

- package-lock.json
- packages/apidom-ns-api-design-systems/package.json
- packages/apidom-ns-api-design-systems/src/validator/openapi-3-1/validator.ts
> refactor(ns-api-design-systems): use apidom-error package

- package-lock.json
- packages/apidom-ns-json-schema-draft-6/package.json
- packages/apidom-ns-json-schema-draft-6/src/elements/JSONSchema.ts
- packages/apidom-ns-json-schema-draft-6/src/elements/LinkDescription.ts
> refactor(ns-json-schema-draft-6): use apidom-error package

- package-lock.json
- packages/apidom-ns-json-schema-draft-7/package.json
- packages/apidom-ns-json-schema-draft-7/src/elements/JSONSchema.ts
- packages/apidom-ns-json-schema-draft-7/src/elements/LinkDescription.ts
> refactor(ns-json-schema-draft-7): use apidom-error package

- package-lock.json
- packages/apidom-parser/README.md
- packages/apidom-parser/package.json
- packages/apidom-parser/src/errors/ParserError.ts
- packages/apidom-parser/src/parser.ts
- packages/apidom-parser/src/types.d.ts
- packages/apidom-parser/test/parser.ts
> refactor(parser): use apidom-error package

- package-lock.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-json/src/lexical-analysis/browser.ts
> refactor(adapter-json): use apidom-error package

- package-lock.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
- packages/apidom-parser-adapter-yaml-1-2/src/lexical-analysis/browser.ts
> refactor(adapter-yaml-1-2): use apidom-error package

- packages/apidom-core/src/deepmerge.ts
- packages/apidom-core/src/media-types.ts
> refactor(core): use more appropriate semantic errors

- packages/apidom-json-pointer-relative/src/compile.ts
- packages/apidom-json-pointer-relative/src/errors/CompilationRelativeJsonPointerError.ts
- packages/apidom-json-pointer-relative/src/errors/EvaluationRelativeJsonPointerError.ts
- packages/apidom-json-pointer-relative/src/errors/InvalidRelativeJsonPointerError.ts
- packages/apidom-json-pointer-relative/src/errors/RelativeJsonPointerError.ts
- packages/apidom-json-pointer-relative/src/errors/index.ts
- packages/apidom-json-pointer-relative/src/evaluate.ts
- packages/apidom-json-pointer-relative/src/index.ts
- packages/apidom-json-pointer-relative/src/parse.ts
> feat(json-pointer-relative): use error hierarchy and metadata when trowing errors

- package-lock.json
- packages/apidom-core/package.json
- packages/apidom-core/src/refractor/plugins/element-identity.ts
- packages/apidom-core/src/refractor/plugins/semantic-element-identity.ts
> chore(deps): bump short-unique-id from 4.4.4 to 5.0.2

- babel.config.cjs
- package-lock.json
- package.json
- packages/apidom-error/src/ApiDOMAggregateError.ts
> fix(error): polyfill AggregateError in older environments

- packages/@types/minim.d.ts
- packages/apidom-core/README.md
- packages/apidom-core/src/clone.ts
- packages/apidom-core/src/index.ts
- packages/apidom-core/test/clone.ts
> feat(core): introduce functions for shallow and deep cloning

- packages/apidom-ast/src/index.ts
- packages/apidom-ast/src/traversal/visitor.ts
- packages/apidom-core/src/index.ts
- packages/apidom-core/src/traversal/visitor.ts
> fix(core): always perform immutable traversal

- packages/apidom-ast/src/traversal/visitor.ts
The changes falls within https://github.com/swagger-api/apidom/blob/79da9ab06385718dd780da811f6bc6a438d2ff07/NOTICE#L12-L14 and MIT license applies.
> feat(ast): apply upstream changes to core visitor/traversal mechanism

- packages/apidom-core/README.md
This function is a 1:1 replacement to freeze method.
> docs(core): provide better documentation for parents function

- packages/apidom-ns-asyncapi-2/src/predicates.ts
- packages/apidom-ns-asyncapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-asyncapi-2/src/refractor/predicates.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/AsyncApiVersionVisitor.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/DefaultContentTypeVisitor.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/IdentifierVisitor.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/info/VersionVisitor.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/async-api-2/message/index.ts
- packages/apidom-ns-asyncapi-2/src/refractor/visitors/generics/PatternedFieldsVisitor.ts
- packages/apidom-ns-asyncapi-2/test/refractor/index.ts
> refactor(ns-asyncapi-2): replace toValue method with function

- packages/apidom-ns-json-schema-draft-4/test/refractor/index.ts
> refactor(ns-json-schema-draft-4): replace toValue method with function

- packages/apidom-ns-json-schema-draft-6/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-json-schema-draft-6/test/refractor/index.ts
> refactor(ns-json-schema-draft-6): replace toValue method with function

- packages/apidom-ns-json-schema-draft-7/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-json-schema-draft-7/test/refractor/index.ts
> refactor(ns-json-schema-draft-7): replace toValue method with function

- packages/apidom-ns-openapi-3-1/src/predicates.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/JsonSchemaDialectVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/WebhooksVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/elements/Schema/embedded-resources-$id.ts
- packages/apidom-ns-openapi-3-1/test/refractor/elements/Schema/embedded-resources-$schema.ts
- packages/apidom-ns-openapi-3-1/test/refractor/index.ts
> refactor(ns-openapi-3-1): replace toValue method with function

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/$anchor/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/util.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/channel-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/example-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/link-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/example-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/path-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts
- packages/apidom-reference/test/parse/index.ts
> refactor(reference): replace toValue method with function

- packages/apidom-ns-openapi-2/README.md
> docs(ns-openapi-2): fix inconsistencies

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/ScopesElement.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/scopes/index.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/Scopes/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/Scopes/index.ts
> feat(ns-openapi-2): add support for Scopes Object

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/SecurityScheme.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/security-scheme/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/SecurityScheme/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/SecurityScheme/index.ts
> feat(ns-openapi-2): add support for Security Scheme Object

- README.md
- package-lock.json
- packages/apidom-logging/.eslintignore
- packages/apidom-logging/.gitignore
- packages/apidom-logging/.mocharc.json
- packages/apidom-logging/.npmrc
- packages/apidom-logging/README.md
- packages/apidom-logging/config/rollup/types.dist.js
- packages/apidom-logging/config/webpack/browser.config.js
- packages/apidom-logging/config/webpack/traits.config.js
- packages/apidom-logging/declaration.tsconfig.json
- packages/apidom-logging/package.json
- packages/apidom-logging/src/Filter.ts
- packages/apidom-logging/src/Filterer.ts
- packages/apidom-logging/src/LogRecord.ts
- packages/apidom-logging/src/LoggingLevel.ts
- packages/apidom-logging/src/index.ts
- packages/apidom-logging/src/styles/StringTemplateStyle.ts
- packages/apidom-logging/src/styles/Style.d.ts
- packages/apidom-logging/src/styles/TemplateLiteralStyle.ts
- packages/apidom-logging/src/styles/index.ts
- packages/apidom-logging/test/.eslintrc
- packages/apidom-logging/test/mocha-bootstrap.cjs
- packages/apidom-logging/tsconfig.json
> feat: add initial implementation of ApiDOM logging facility

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/Xml.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/xml/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/Xml/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/Xml/index.ts
> feat(ns-openapi-2): add support for XML Object

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/ExternalDocumentation.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/external-documentation/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/ExternalDocumentation/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/ExternalDocumentation/index.ts
> feat(ns-openapi-2): add support for External Documentation Object

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/Contact.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/contact/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/Contact/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/Contact/index.ts
> feat(ns-openapi-2): add support for Contact Object

- packages/apidom-ns-openapi-2/test/refractor/elements/Items/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/Items/index.ts
> test(ns-openapi-2): add test for recursive Items Object

- package-lock.json
- package.json
- packages/apidom-parser-adapter-json/src/lexical-analysis/browser-patch.ts
- packages/apidom-parser-adapter-yaml-1-2/src/lexical-analysis/browser-patch.ts
> chore(deps-dev): bump @types/node from 20.8.3 to 20.8.4

- packages/apidom-logging/src/Filterer.ts
- packages/apidom-logging/src/Formatter.ts
- packages/apidom-logging/src/LogRecord.ts
- packages/apidom-logging/src/styles/StringTemplateStyle.ts
- packages/apidom-logging/src/styles/Style.d.ts
- packages/apidom-logging/src/styles/TemplateLiteralStyle.ts
- packages/apidom-logging/src/styles/index.ts
> feat(logging): add initial implementation of Formatter

- package-lock.json
- packages/apidom-ns-openapi-2/package.json
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
> fix(ns-openapi-2): add support for JSONReferenceElement

- packages/apidom-ns-openapi-2/src/refractor/specification.ts
> refactor(ns-openapi-2): use references in spec object

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/PathItem.ts
- packages/apidom-ns-openapi-2/src/elements/nces/PathItemParameters.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/generics/AlternatingVisitor.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/path-item/$RefVisitor.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/path-item/ParametersVisitor.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/path-item/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/PathItem/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/PathItem/index.ts
> feat(ns-openapi-2): add support for PathItem Object

- packages/apidom-ns-openapi-2/README.md
- packages/apidom-ns-openapi-2/src/elements/Paths.ts
- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/namespace.ts
- packages/apidom-ns-openapi-2/src/predicates.ts
- packages/apidom-ns-openapi-2/src/refractor/registration.ts
- packages/apidom-ns-openapi-2/src/refractor/specification.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/open-api-2/paths/index.ts
- packages/apidom-ns-openapi-2/src/traversal/visitor.ts
- packages/apidom-ns-openapi-2/test/predicates.ts
- packages/apidom-ns-openapi-2/test/refractor/elements/Paths/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/elements/Paths/index.ts
> feat(ns-openpai-2): add support for Paths Object

- packages/apidom-ns-openapi-2/src/index.ts
- packages/apidom-ns-openapi-2/src/refractor/plugins/replace-empty-element.ts
- packages/apidom-ns-openapi-2/test/refractor/plugins/replace-empty-element/__snapshots__/mappings.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/plugins/replace-empty-element/__snapshots__/sequences.ts.snap
- packages/apidom-ns-openapi-2/test/refractor/plugins/replace-empty-element/mappings.ts
- packages/apidom-ns-openapi-2/test/refractor/plugins/replace-empty-element/sequences.ts
> feat(ns-openapi-2): add replace empty elements refractor plugin

- packages/apidom-logging/src/Formatter.ts
- packages/apidom-logging/src/LogRecord.ts
- packages/apidom-logging/src/index.ts
> feat(logging): finish Formatter implementation

- package-lock.json
- packages/apidom-reference/README.md
- packages/apidom-reference/package.json
- packages/apidom-reference/src/configuration/saturated.ts
- packages/apidom-reference/src/parse/parsers/openapi-yaml-2/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-yaml-2/fixtures/sample-api.yaml
- packages/apidom-reference/test/parse/parsers/openapi-yaml-2/index.ts
> feat(reference): add OpenAPI 2.0 YAML parser plugin

- packages/apidom-logging/src/Logger.ts
- packages/apidom-logging/src/Placeholder.ts
> feat(logging): add Placeholder implementation

- packages/apidom-ns-openapi-3-0/src/index.ts
- packages/apidom-ns-openapi-3-0/src/predicates.ts
- packages/apidom-ns-openapi-3-1/src/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-servers.ts
- packages/apidom-ns-openapi-3-1/src/refractor/toolbox.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/index.ts
Refs https://github.com/swagger-api/swagger-js/issues/2967
Refs https://github.com/OAI/OpenAPI-Specification/issues/3427
> fix(ns-openapi-3-1): fix normalize-servers refractor plugin

- packages/apidom-ns-workflows-1/src/media-types.ts
> fix(ns-workflows-1): use proper version in media types

- packages/apidom-reference/test/dereference/strategies/openapi-2/parameter-object/fixtures/operation-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/parameter-object/fixtures/operation-object/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/parameter-object/fixtures/path-item-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/parameter-object/fixtures/path-item-object/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/parameter-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/response-object/fixtures/responses-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/response-object/fixtures/responses-object/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/response-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/definitions/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/definitions/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/parameter-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/parameter-object/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/response-object/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/fixtures/response-object/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/schema-object/index.ts
> test(reference): add location tests for OpenAPI 2.0 dereference

- package-lock.json
- package.json
> chore(deps-dev): bump lerna from 7.4.2 to 8.0.0

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-3-0/visitor.ts
This change affects all dereference and resolution strategies.
Refs #3451
> fix(reference): lazy fetch URLs only when needed

- packages/apidom-ls/src/services/validation/linter-functions.ts
> fix(ls): add missing swagger root ApiDOM element type

- README.md
- packages/apidom-ns-workflows-1/package.json
> chore(ns-workflows-1): prepare for the first release

- package-lock.json
- packages/apidom-playground/package.json
> chore(playground): update swagger-adjust to v0.6.1

- packages/apidom-ls/src/config/openapi/parameter/completion.ts
> feat(ls): add completion rules for OpenAPI 2.0 Parameter Object

- packages/apidom-core/src/transformers/from.ts
Refs https://github.com/swagger-api/swagger-ui/issues/9466#issuecomment-1881053410 
Refs https://github.com/parcel-bundler/parcel/issues/9473
> fix(core): allow Parcel.js to bundle the code

- packages/apidom-ast/src/Error.ts
- packages/apidom-ast/src/Literal.ts
- packages/apidom-ast/src/Node.ts
- packages/apidom-ast/src/Position.ts
- packages/apidom-core/src/elements/SourceMap.ts
- packages/apidom-parser-adapter-json/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
- packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
> AST base nodes

- packages/apidom-ast/src/yaml/schemas/ScalarTag.ts
- packages/apidom-ast/src/yaml/schemas/Tag.ts
- packages/apidom-ast/src/yaml/schemas/failsafe/GenericMapping.ts
- packages/apidom-ast/src/yaml/schemas/failsafe/GenericSequence.ts
- packages/apidom-ast/src/yaml/schemas/failsafe/GenericString.ts
- packages/apidom-ast/src/yaml/schemas/failsafe/index.ts
- packages/apidom-ast/src/yaml/schemas/json/Boolean.ts
- packages/apidom-ast/src/yaml/schemas/json/FloatingPoint.ts
- packages/apidom-ast/src/yaml/schemas/json/Integer.ts
- packages/apidom-ast/src/yaml/schemas/json/Null.ts
- packages/apidom-ast/src/yaml/schemas/json/index.ts
> refactor(ast): followup changes for YAML 1.2 Schemas

- packages/apidom-ast/src/Node.ts
- packages/apidom-ast/src/predicates.ts
- packages/apidom-ast/src/yaml/nodes/YamlAlias.ts
- packages/apidom-ast/src/yaml/nodes/YamlAnchor.ts
- packages/apidom-ast/src/yaml/nodes/YamlComment.ts
- packages/apidom-ast/src/yaml/nodes/YamlDirective.ts
- packages/apidom-ast/src/yaml/nodes/YamlKeyValuePair.ts
- packages/apidom-ast/src/yaml/nodes/YamlNode.ts
- packages/apidom-ast/src/yaml/nodes/YamlScalar.ts
- packages/apidom-ast/src/yaml/nodes/YamlStyle.ts
- packages/apidom-ast/src/yaml/nodes/YamlTag.ts
- packages/apidom-ast/src/yaml/nodes/predicates.ts
- packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
> refactor(ast): followup changes for YAML 1.2 Nodes

- packages/apidom-ast/src/json/nodes/JsonArray.ts
- packages/apidom-ast/src/json/nodes/JsonDocument.ts
- packages/apidom-ast/src/json/nodes/JsonEscapeSequence.ts
- packages/apidom-ast/src/json/nodes/JsonFalse.ts
- packages/apidom-ast/src/json/nodes/JsonKey.ts
- packages/apidom-ast/src/json/nodes/JsonNull.ts
- packages/apidom-ast/src/json/nodes/JsonNumber.ts
- packages/apidom-ast/src/json/nodes/JsonObject.ts
- packages/apidom-ast/src/json/nodes/JsonProperty.ts
- packages/apidom-ast/src/json/nodes/JsonString.ts
- packages/apidom-ast/src/json/nodes/JsonStringContent.ts
- packages/apidom-ast/src/json/nodes/JsonTrue.ts
- packages/apidom-ast/src/json/nodes/JsonValue.ts
- packages/apidom-ast/src/json/nodes/predicates.ts
- packages/apidom-ast/src/yaml/nodes/YamlAlias.ts
- packages/apidom-ast/src/yaml/nodes/YamlAnchor.ts
- packages/apidom-ast/src/yaml/nodes/YamlComment.ts
- packages/apidom-ast/src/yaml/nodes/YamlDirective.ts
- packages/apidom-ast/src/yaml/nodes/YamlDocument.ts
- packages/apidom-ast/src/yaml/nodes/YamlKeyValuePair.ts
- packages/apidom-ast/src/yaml/nodes/YamlMapping.ts
- packages/apidom-ast/src/yaml/nodes/YamlScalar.ts
- packages/apidom-ast/src/yaml/nodes/YamlSequence.ts
- packages/apidom-ast/src/yaml/nodes/YamlStream.ts
- packages/apidom-ast/src/yaml/nodes/YamlTag.ts
> refactor(ast): followup changes for JSON Nodes

- package-lock.json
- package.json
- packages/apidom-ls/src/services/validation/validation-service.ts
- packages/apidom-ls/src/utils/utils.ts
> chore(deps-dev): bump prettier from 3.1.1 to 3.2.4

- packages/apidom-ls/src/config/common/schema/lint/type--equals.ts
> refactor(ls): remove unique option from apilintValueOrArray lint

- packages/apidom-ls/src/config/common/schema/completion.ts
- packages/apidom-ls/test/complete.ts
> feat(ls): add completion rules for OpenAPI 2.0 Schema Object

- packages/apidom-ns-api-design-systems/src/refractor/specification.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/FallbackVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/info/DescriptionVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/info/TitleVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/PrinciplesVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/ScenariosVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/StandardsVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/VersionVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/principle/DescriptionVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/principle/IriVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/principle/NameVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/principle/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/requirement/FollowsVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/requirement/ValuesVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/requirement/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/scenario/DescriptionVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/scenario/ThenVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/scenario/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard/DescriptionVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard/IriVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard/NameVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/generics/FixedFieldsVisitor.ts
> refactor(ns-ads): increase visitors TypeScript type safety

- packages/apidom-ns-api-design-systems/src/refractor/visitors/SpecificationVisitor.ts
- packages/apidom-ns-workflows-1/src/refractor/visitors/SpecificationVisitor.ts
This is TypeScript related change.
Refs #3481
> refactor: remove unnecessary definitive assignment marker

- package-lock.json
- packages/apidom-converter/test/mocha-bootstrap.cjs
- packages/apidom-playground/package.json
It SHOULD address (false positive) linting issues detected in https://github.com/swagger-api/apidom/actions/runs/7711289380/job/21016359956
> chore(deps): regenerate package-lock.json

- packages/apidom-ls/src/config/asyncapi/message-trait/lint/examples--type.ts
> fix(ls): fix linting rule for MessageTrait.exammples field

- packages/apidom-ls/src/config/asyncapi/bindings/anypointmq/message-binding/lint/0-0-1/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/anypointmq/message-binding/lint/latest/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/http/message-binding/lint/0-1-0/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/http/message-binding/lint/latest/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/http/operation-binding/lint/0-1-0/query--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/http/operation-binding/lint/latest/query--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/ws/channel-binding/lint/0-1-0/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/ws/channel-binding/lint/0-1-0/query--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/ws/channel-binding/lint/latest/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/bindings/ws/channel-binding/lint/latest/query--type.ts
- packages/apidom-ls/src/config/asyncapi/message-trait/lint/headers--type.ts
- packages/apidom-ls/src/config/asyncapi/message/lint/headers--type.ts
> fix(ls): allow AsyncAPI 2.0 Schema Object to be Boolean JSON Schema

- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/WebhooksVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/callback/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/components/PathItemsVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/components/SchemasVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/distriminator/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/index.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/$defsVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/DependentSchemasVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/PatternPropertiesVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/PropertiesVisitor.ts
- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/index.ts
> refactor(ns-openapi-3-1): enhance visitor encapsulation

- .husky/commit-msg
- .husky/pre-commit
- package-lock.json
- package.json
> chore(deps-dev): bump husky from 8.0.3 to 9.0.10

- packages/apidom-ast/src/index.ts
- packages/apidom-ast/src/yaml/anchors-aliases/ReferenceManager.ts
- packages/apidom-ast/src/yaml/errors/YamlError.ts
- packages/apidom-ast/src/yaml/errors/YamlReferenceError.ts
- packages/apidom-ast/src/yaml/errors/YamlSchemaError.ts
- packages/apidom-ast/src/yaml/nodes/predicates.ts
- packages/apidom-parser-adapter-yaml-1-2/src/syntactic-analysis/indirect/visitors/CstVisitor.ts
> refactor(ast): register YAML nodes with anchors, not just anchors

- packages/apidom-reference/src/util/url.ts
> refactor(reference): migrate to String.prototype.substring

- packages/apidom-ns-api-design-systems/src/refractor/visitors/SpecificationVisitor.ts
- packages/apidom-ns-json-schema-draft-4/src/refractor/visitors/SpecificationVisitor.ts
- packages/apidom-ns-openapi-2/src/refractor/visitors/SpecificationVisitor.ts
- packages/apidom-ns-workflows-1/src/refractor/visitors/SpecificationVisitor.ts
> fix: refracting semantic ApiDOM

- packages/apidom-ns-api-design-systems/src/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/info/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/PrinciplesVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/ScenariosVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/StandardsVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/main/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/principle/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/requirement-level/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/requirement/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/scenario/ThenVisitor.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/scenario/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard-identifier/index.ts
- packages/apidom-ns-api-design-systems/src/refractor/visitors/api-design-systems/standard/index.ts
> feat(ns-ads): export symbols and types

- packages/apidom-core/src/identity/index.ts
- packages/apidom-core/src/refractor/plugins/element-identity.ts
- packages/apidom-core/src/refractor/plugins/semantic-element-identity.ts
- packages/apidom-core/test/refractor/plugins/element-identity.ts
- packages/apidom-core/test/refractor/plugins/semantic-element-identity.ts
> fix(core): assign unique ID to elements only when missing

- packages/apidom-core/src/refractor/index.ts
- packages/apidom-core/test/refractor/elements/Comment/__snapshots__/index.ts.snap
- packages/apidom-core/test/refractor/elements/Comment/index.ts
> fix(core): retain meta & attributes during refracting

- packages/apidom-core/README.md
- packages/apidom-core/src/index.ts
- packages/apidom-core/src/merge/merge-left.ts
- packages/apidom-core/test/index.ts
- packages/apidom-core/test/merge/merge-left.ts
- packages/apidom-core/test/merge/merge-right.ts
> feat(core): add mechanism for left shallow merge

- packages/apidom-core/src/index.ts
- packages/apidom-core/src/merge/deepmerge.ts
- packages/apidom-core/src/merge/merge-right.ts
- packages/apidom-core/test/merge/deepmerge.ts
> refactor(core): consolidate merge algorithms

- packages/apidom-core/package.json
- packages/apidom-playground/src/playground/apidom.worker.js
The bug was introduced by changes in #3481.
Refs #3481
> fix(playground): fix bug related to instantiating parser

- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/fixtures/external-cycle/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/fixtures/external-cycle/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/fixtures/external-cycle/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/fixtures/external-cycle/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/index.ts
> fix(reference): add support for external cycles detection in OpenAPI 3.0.x

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-cycle/ex.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-cycle/root.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
> fix(reference): add support for external cycles detection in AsyncAPI 2.x dereference strategy

- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/external-cycle/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/fixtures/external-cycle/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
> fix(reference): add support for external cycles detection in OpenAPI 3.1.0 dereference strategy

- packages/apidom-reference/README.md
- packages/apidom-reference/package.json
- packages/apidom-reference/src/configuration/saturated.ts
- packages/apidom-reference/src/parse/parsers/apidom-json/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-json/fixtures/apidom.json
- packages/apidom-reference/test/parse/parsers/apidom-json/index.ts
> feat(reference): add parser plugin for parsing hydrated ApiDOM

- packages/apidom-core/src/transformers/serializers/value/ast/ephemeral-array.ts
- packages/apidom-core/src/transformers/serializers/value/ast/ephemeral-object.ts
- packages/apidom-core/src/transformers/serializers/value/index.ts
- packages/apidom-core/test/transformers/serializers/value.ts
> feat(core): handle RefElement serialization in toValue serialization

- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
> feat(reference): add support for skipping internal references in OpenAPI 3.0.x dereference strategy

- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
> feat(reference): add support for skipping internal references in OpenAPI 3.1.0 dereference strategy

- packages/apidom-reference/src/ReferenceSet.ts
- packages/apidom-reference/src/dereference/strategies/apidom/index.ts
- packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/index.ts
- packages/apidom-reference/src/resolve/strategies/apidom/index.ts
- packages/apidom-reference/src/resolve/strategies/apidom/visitor.ts
- packages/apidom-reference/test/dereference/strategies/apidom/local/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/index.ts
> feat(reference): apply dereferencing architecture 2.0 to ApiDOM

- packages/apidom-reference/src/dereference/strategies/apidom/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/resolve/strategies/openapi-2/index.ts
- packages/apidom-reference/src/resolve/strategies/openapi-2/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/fixtures/cycle-internal/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts
> feat(reference): apply dereferencing architecture 2.0 to OpenAPI 2.0

- packages/apidom-reference/src/dereference/strategies/apidom/index.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/index.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/index.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/index.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/index.ts
- packages/apidom-reference/src/resolve/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
> feat(reference): apply dereferencing architecture 2.0 to AsyncAPI 2.x

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$id-uri-external-circular-structures/dereferenced.txt
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$id-uri-external-circular-structures/nested/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$id-uri-external-circular-structures/nested/nested/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/$id-uri-external-circular-structures/root.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts
> fix(reference): fix regression in nested paths dereferencing

- packages/apidom-ls/src/services/validation/validation-service.ts
> perf(ls): apply perfomanze optimization for reference validation

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only/ex.json
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/fixtures/external-only/root.json
> fix(reference): fix regression in AsyncAPI 2.x dereferencing

- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/external-only/dereferenced.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/external-only/ex.json
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/fixtures/external-only/root.json
> fix(reference): fix regression in OpenAPI 3.1.0 dereferencing

- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
> perf(reference): dereference fragments as quick as possible

- packages/apidom-ast/src/index.ts
- packages/apidom-ast/src/traversal/visitor.ts
> feat(ast): introduce async visitor merging mechanism

- packages/apidom-ast/src/index.ts
- packages/apidom-ast/src/traversal/visitor.ts
- packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
- packages/apidom-core/src/index.ts
- packages/apidom-core/src/refractor/index.ts
- packages/apidom-core/src/refractor/plugins/dispatcher/index.ts
- packages/apidom-core/src/refractor/plugins/utils/index.ts
- packages/apidom-core/test/refractor/plugins/dispatcher/index.ts
- packages/apidom-core/test/refractor/plugins/utils/index.ts
> feat(core): introduce async version of visitor merging mechanism

- packages/apidom-converter/src/strategies/openapi-3-1-to-openapi-3-0-3/index.ts
> feat(converter): add support for asynchronous conversion plugins

- packages/apidom-core/test/refractor/plugins/dispatcher/index.ts
> test(core): add test for throwing while dispatching async plugins in sync mode

- packages/apidom-playground/src/playground/components/left-pane/Editor.jsx
> fix(playground): fix recurstion related to textarea sizing

- package-lock.json
- packages/apidom-core/package.json
- packages/apidom-core/src/identity/index.ts
- packages/apidom-core/src/refractor/plugins/element-identity.ts
- packages/apidom-core/src/refractor/plugins/semantic-element-identity.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
Refs #3481
---
This introduces a breaking change in `@swagger-api/apidom-core` public API.
> refactor(core): change from stamps to TypeScript classes

- .github/workflows/release.yml
- lerna.json
> ci(release): prepare CD pipeline for 1.0.0-alpha.0 release

- packages/apidom-ast/src/traversal/visitor.ts
- packages/apidom-ast/test/traversal/visitor.ts
- packages/apidom-core/test/refractor/index.ts
- packages/apidom-ns-api-design-systems/test/refractor/index.ts
- packages/apidom-ns-asyncapi-2/test/refractor/index.ts
- packages/apidom-ns-json-schema-draft-4/test/refractor/index.ts
- packages/apidom-ns-json-schema-draft-6/test/refractor/index.ts
- packages/apidom-ns-json-schema-draft-7/test/refractor/index.ts
- packages/apidom-ns-openapi-2/test/refractor/index.ts
- packages/apidom-ns-openapi-3-0/test/refractor/index.ts
- packages/apidom-ns-openapi-3-1/test/refractor/index.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
> feat(ast): add support for mutable node replacments (edits)

- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameters.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/__snapshots__/idempotence.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/callbacks/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/idempotence.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/paths/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/storage-field.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameters/web-hooks/__snapshots__/index.ts.snap
> feat(ns-openapi-3-1): make parameters refractor plugin idempotent

- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-operation-ids.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/__snapshots__/idempotence.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/idempotence.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-operation-ids/storage-fields.ts
> feat(ns-openapi-3-1): make operation ids refractor plugin idempotent

- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-servers.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/__snapshots__/idempotence.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/__snapshots__/index.ts.snap
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/idempotence.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-servers/storage-fields.ts
> feat(ns-openapi-3-1): make servers refractor plugin idempotent

- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameter-examples.ts
- packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameter-examples/paths/__snapshots__/index.ts.snap
> fix(ns-openapi-3-1): set example to first element of examples in parameter examples refractor plugin

- packages/apidom-reference/src/parse/parsers/api-design-systems-json/index.ts
- packages/apidom-reference/src/parse/parsers/api-design-systems-yaml/index.ts
- packages/apidom-reference/src/parse/parsers/apidom-json/index.ts
- packages/apidom-reference/src/parse/parsers/asyncapi-json-2/index.ts
- packages/apidom-reference/src/parse/parsers/asyncapi-yaml-2/index.ts
- packages/apidom-reference/src/parse/parsers/json/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-json-2/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-json-3-0/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-json-3-1/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-yaml-2/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-yaml-3-0/index.ts
- packages/apidom-reference/src/parse/parsers/openapi-yaml-3-1/index.ts
- packages/apidom-reference/src/parse/parsers/workflows-json-1/index.ts
- packages/apidom-reference/src/parse/parsers/workflows-yaml-1/index.ts
- packages/apidom-reference/src/parse/parsers/yaml-1-2/index.ts
- packages/apidom-reference/test/mocha-bootstrap.cjs
- packages/apidom-reference/test/parse/parsers/api-design-systems-json/index.ts
- packages/apidom-reference/test/parse/parsers/api-design-systems-yaml/index.ts
- packages/apidom-reference/test/parse/parsers/apidom-json/index.ts
- packages/apidom-reference/test/parse/parsers/asyncapi-json-2/index.ts
- packages/apidom-reference/test/parse/parsers/asyncapi-yaml-2/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-json-2/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-json-3-0/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-json-3-1/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-yaml-2/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-yaml-3-0/index.ts
- packages/apidom-reference/test/parse/parsers/openapi-yaml-3-1/index.ts
- packages/apidom-reference/test/parse/parsers/workflows-json-1/index.ts
- packages/apidom-reference/test/parse/parsers/workflows-yaml-1/index.ts
- packages/apidom-reference/test/parse/parsers/yaml/index.ts
> feat(reference): loosen requirement for file extensions in parser plugins

- package-lock.json
- package.json
- packages/apidom-ast/src/traversal/visitor.ts
> chore(deps-dev): bump prettier from 3.3.2 to 3.3.3

- package-lock.json
- package.json
- packages/apidom-core/package.json
> chore(deps-dev): bump typescript from 5.4.5 to 5.5.4

- packages/apidom-reference/package.json
> chore(deps): make sure we're use axios >= 1.7.4

- package-lock.json
- packages/apidom-playground/package.json
> chore(deps): bump @mui/icons-material from 5.16.7 to 6.1.4

- packages/apidom-json-path/src/polyfills.ts
> build(json-path): use file extensions when using core-js-pure

- packages/apidom-parser-adapter-api-design-systems-json/.eslintrc
- packages/apidom-parser-adapter-api-design-systems-json/package.json
- packages/apidom-parser-adapter-api-design-systems-json/src/adapter.ts
- packages/apidom-parser-adapter-api-design-systems-json/test/adapter.ts
- packages/apidom-parser-adapter-api-design-systems-json/test/media-types.ts
- packages/apidom-parser-adapter-api-design-systems-json/test/mocha-bootstrap.ts
- packages/apidom-parser-adapter-api-design-systems-json/test/tsconfig.json
- packages/apidom-parser-adapter-api-design-systems-json/tsconfig.declaration.json
- packages/apidom-parser-adapter-api-design-systems-json/tsconfig.json
> build(parser-adapter-api-design-systems-json): use nodenext for TypeScript modules

- packages/apidom-json-pointer/package.json
> fix(json-pointer): fix non existing package entry point

- package-lock.json
- packages/apidom-parser-adapter-json/package.json
- packages/apidom-parser-adapter-yaml-1-2/package.json
- packages/apidom-parser-adapter-yaml-1-2/test/__snapshots__/adapter-browser.mjs.snap
- packages/apidom-parser-adapter-yaml-1-2/test/adapter-browser.ts
- packages/apidom-parser-adapter-yaml-1-2/test/adapter-node/__snapshots__/index.mjs.snap
- packages/apidom-parser-adapter-yaml-1-2/test/adapter-node/index.ts
> fix(parser-adapter-yaml-1-2): fix parsing long object keys

- packages/apidom-ns-openapi-3-0/test/refractor/elements/Openapi/__snapshots__/index.mjs.snap
> test(ns-openapi-3-0): regenerate obsolete snapshot

- packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-servers.ts
The update reflects latest changes from OpenAPI 3.1.1
> docs(ns-openapi-3-1): update normalize servers refractor plugin docs

- packages/apidom-ns-openapi-3-0/README.md
- packages/apidom-ns-openapi-3-0/test/refractor/__snapshots__/index.mjs.snap
- packages/apidom-ns-openapi-3-0/test/refractor/fixtures/openapi.json
- packages/apidom-ns-openapi-3-0/test/refractor/index.ts
- packages/apidom-ns-openapi-3-0/test/refractor/plugins/replace-empty-element/mappings.ts
- packages/apidom-ns-openapi-3-0/test/refractor/plugins/replace-empty-element/sequences.ts
> docs(ns-openapi-3-0): adapt to having OpenAPI 3.0.4 support

- packages/apidom-parser-adapter-openapi-json-3-0/README.md
> docs(parser-adapter-openapi-json-3-0): adapt to OpenAPI 3.0.4 support

- package-lock.json
- packages/apidom-ls/package.json
- packages/apidom-ls/src/services/validation/linter-functions.ts
> chore(deps): bump openapi-path-templating to 2.0.1

- packages/apidom-ns-json-schema-draft-7/README.md
- packages/apidom-ns-json-schema-draft-7/src/elements/JSONSchema.ts
- packages/apidom-ns-json-schema-draft-7/src/elements/LinkDescription.ts
> fix(ns-json-schema-draft-7): add missing method overrides

- packages/apidom-ns-openapi-3-1/src/refractor/visitors/open-api-3-1/schema/$defsVisitor.ts
> fix(ns-openapi-3-1): import only JSON Schema 2020-12 namespace

- package-lock.json
- packages/apidom-core/package.json
- packages/apidom-parser-adapter-json/test/tsconfig.json
- packages/apidom-parser-adapter-yaml-1-2/test/tsconfig.json
Later versions are having issues with TypeScript typings.
Refs https://github.com/simplyhexagonal/short-unique-id/issues/65
> chore(deps): pin short-unique-id to v5.2.0

- package-lock.json
- packages/apidom-playground/.eslintrc
- packages/apidom-playground/package.json
- packages/apidom-playground/src/playground/components/DereferenceDialog.jsx
- packages/apidom-playground/src/playground/components/left-pane/Editor.jsx
- packages/apidom-playground/src/playground/components/left-pane/EditorControls.jsx
- packages/apidom-playground/src/playground/components/left-pane/LeftPane.jsx
- packages/apidom-playground/src/playground/components/right-pane/RightPane.jsx
> chore(deps): update @mui/* packages

- package-lock.json
- packages/apidom-json-path/package.json
- packages/apidom-json-path/src/evaluate-multi.ts
- packages/apidom-json-path/src/evaluate.ts
- packages/apidom-json-pointer/package.json
- packages/apidom-json-pointer/src/evaluate.ts
This is continuation of the plan aligned in https://github.com/swagger-api/apidom/pull/4870
> fix(json-path): use spec compliant JSON Pointer evaluation

- packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
- packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/uri.ts
- packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/channel-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/path-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/example-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/link-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/link-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/example-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/path-item-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/dereference-apidom.ts
- packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts
- packages/apidom-reference/test/tsconfig.json
> fix(reference): use spec compliant JSON Pointer implementation
